### ISSUE TITLE
No output shown when executing script

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#1]
Every time, Octave asks to change the current directory or add it to the path. No variables are created and the command line doesn't show any output.

**Comment by Alexander-Wilms** [comment]
@mtmiller Do you know how I could debug this and #2 ?

**Comment by mtmiller** [comment]
Unreproducible here. Are you choosing "Cancel" in the prompt? What is the full path of the script?

**Comment by Alexander-Wilms** [comment]
I can execute the script, if I manually change the current directory. The "change directory" and "add directory to search path" buttons do nothing.

**Comment by mtmiller** [comment]
Sounds like the bug is the dialog buttons not working as expected on your system. I have tried in the English and German locales and both work for me.

It looks like it is responding as if you pressed "Cancel" and not executing any commands. I would try printing out the value of the button text in the `octave_qt_link::do_debug_cd_or_addpath_error` function. Maybe something is wrong with the button text string comparison.

**Comment by Alexander-Wilms** [comment]
Thanks for the hint, I'll try that.

**Comment by Alexander-Wilms** [comment]
The issue persists with a non-flatpak build. Looks like it's the same issue with KDE that also broke the variable editor: an ampersand gets appended at the beginning of the string.

**Comment by mtmiller** [comment]
Good find. I don't use KDE. Will you file a bug upstream?

**Comment by Alexander-Wilms** [comment]
Another bug caused by the ampersand was closed: https://savannah.gnu.org/bugs/?51853
Should I open a new one anyway?

**Comment by mtmiller** [comment]
I think so. I wasn't paying much attention, but [#51905](https://savannah.gnu.org/bugs/?51905) was fixed while [#51853](https://savannah.gnu.org/bugs/?51853) wasn't. They are similar, but one was fixed and I guess the other was considered cosmetic. This one seems more important to me than the title bar looking wrong.

**Comment by Alexander-Wilms** [comment]
Okay, done: https://savannah.gnu.org/bugs/index.php?52423
