### ISSUE TITLE
Drop osmesa from build

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#10]
Octave now uses QOffscreenSurface for working with invisible figures. As long as Qt includes that class (any recent Qt >= 5.1), Octave doesn't need OSMesa at all anymore.

@Alexander-Wilms was OSMesa the only reason for including the `mesa` module in the manifest?

**Comment by Alexander-Wilms** [comment]
I think so. It was probably listed when ./configuring, so I added it.

**Comment by mtmiller** [comment]
Done on the 4.4 branch
