### ISSUE TITLE
waitforbuttonpress() crashes octave with signal 11

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.octave.Octave#103]
Using waitforbuttonpress() crashes octave from flathub. The error is:
```
octave exited with signal 11
```

Octave from the arch repositories (which seems to be at the same version) works without issues.

**Comment by mtmiller** [comment]
It works for me.

```
>> button = waitforbuttonpress ()
button = 0
```

Is there a more complete example that demonstrates the crash for you? Can you open any figure or plot data at all? Can you identify what or where specifically the crash occurs?

**Comment by ThanosApostolou** [comment]
Can you try something with plot() and then waitforbuttonpress()?

For example this code runs fine on arch packaged octave but crashes the flatpak one:
```
clear all
close all
clc

Fs=1000;
Ts=1/Fs;
T=0.2;
t=0:Ts:T-Ts; 
A=1;
x=A*sin(2*pi*50*t);
L=length(x);
plot(t,x)
waitforbuttonpress()
```

**Comment by mtmiller** [comment]
Sure, still no crash for me.

**Comment by ThanosApostolou** [comment]
Really weird, it was working for me too a couple of weeks ago and reverting to a previous commit (which I see it was 14 days ago) didn't fix it for me either. Is there any way to get more debugging messages or something because the error output from terminal is very short:
```
$ flatpak run org.octave.Octave --gui
octave exited with signal 11
```

**Comment by mtmiller** [comment]
You could start with something like

    flatpak run --devel --command=gdb org.octave.Octave --args \
      /app/libexec/octave/5.2.0/exec/x86_64-pc-linux-gnu/octave-gui --gui

and then proceed with gdb `run` and other commands as usual. You might also want to install `org.octave.Octave.Debug` from flathub to get debug symbols.

**Comment by ThanosApostolou** [comment]
Ok here is the full output:
https://pastebin.com/fEUZ5WXF

The Segmentation Fault appears the moment I click on the opened window of the plot, so when the waitforbuttonpress() is triggered.

**Comment by mtmiller** [comment]
May have something to do with the last line there

```
0x00007fffd064e248 in ?? () from /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so
```

Could be some kind of issue between Flatpak and the Mesa AMD Radeon user-space driver.

**Comment by Alexander-Wilms** [comment]
@ThanosApostolou Can you test if this is fixed with newer drivers?

**Comment by ThanosApostolou** [comment]
@Alexander-Wilms There have been years since I had this issue, but I tested the code that I have put in the comment https://github.com/flathub/org.octave.Octave/issues/103#issuecomment-603540486 and it works properly now without crushing. So, the issue seems to have been resolved, feel free to close this.

**Comment by Alexander-Wilms** [comment]
Thanks for testing, perhaps it really was an issue with the graphics driver.
