### ISSUE TITLE
Frequent GUI Crashes on Wayland

### ISSUE THREAD

**Issue by dasebek** [flathub/org.octave.Octave#106]
This Flatpak version of Octave uses Wayland by default. However, the GUI is very unstable and crashes often. The easiest way to reproduce a crash is to run Octave in the GUI mode, click File, move the mouse cursor over the first item in the menu (New), and then move the cursor up over the Edit button. The window closes immediately and Octave prints "octave exited with signal 6" to the console. Launching Octave with --nosocket=wayland forces it to use X11 instead and the GUI becomes very stable. Maybe X11 should be enforced by default in case this problem is caused by QT libraries and not by Octave itself.
I use Fedora 31 and 32 with the default GNOME environment.

**Comment by mtmiller** [comment]
Confirmed. I also get similar crashes with other KDE / Qt / Wayland applications, for example org.kde.kate. So seems likely that it's a problem with the framework or the Wayland interface.

**Comment by Alexander-Wilms** [comment]
Can no longer reproduce the issue
