### ISSUE TITLE
Run test suite as part of Flatpak build

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#114]
Should we add `make check` to the Octave module of the manifest?

**Comment by siko1056** [comment]
As far as I remember, due to bugs like #95 it is possible that depending on the builder `make check` might fail.  But in general nothing really speaks against it, it will extend the build time by about 5 to 15 minutes, as it is quite comprehensive :wink:

**Comment by Alexander-Wilms** [comment]
You are right, the test build failed due to the audiodevinfo issue: https://github.com/flathub/org.octave.Octave/pull/119#issuecomment-782743017
