### ISSUE TITLE
Reducing Flatpak bundle size

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#12]
https://flathub.org/builds/#/builders/2/builds/286 shows a size of 501.4 MB (x86) respective 444.0 MB (x86_64) (edit: that's for the repo, not the .flatpak bundle).

What can be removed:

/app/examples
/app/man
/app/share/doc <- will the new Octave documentation end up here?
/app/share/applications/fluid.desktop
/app/share/hdf5_examples
/app/include/QSci

Which other header files in /app/include are not needed for building any Octave packages?

Directories in /app/include:
```
arkode/  cvode/  cvodes/  FL/  GL/  GraphicsMagick/  ida/  idas/  kinsol/  libqhull/  libqhullcpp/  libqhull_r/  nvector/  Qsci/  sundials/
```
Files in /app/include:

```
amd.h
btf.h
camd.h
cblas.h
ccolamd.h
cholmod_blas.h
cholmod_camd.h
cholmod_check.h
cholmod_cholesky.h
cholmod_complexity.h
cholmod_config.h
cholmod_core.h
cholmod_function.h
cholmod_gpu.h
cholmod_gpu_kernels.h
cholmod.h
cholmod_io64.h
cholmod_matrixops.h
cholmod_modify.h
cholmod_partition.h
cholmod_supernodal.h
cholmod_template.h
colamd.h
cs.h
f77blas.h
fftw3.f
fftw3.f03
fftw3.h
fftw3l.f03
fftw3q.f03
gl2ps.h
glpk.h
H5ACpublic.h
H5api_adpt.h
H5Apublic.h
H5Cpublic.h
H5DOpublic.h
H5Dpublic.h
H5DSpublic.h
H5Epubgen.h
H5Epublic.h
H5FDcore.h
H5FDdirect.h
H5FDfamily.h
H5FDlog.h
H5FDmpi.h
H5FDmpio.h
H5FDmulti.h
H5FDpublic.h
H5FDsec2.h
H5FDstdio.h
H5Fpublic.h
H5Gpublic.h
H5IMpublic.h
H5Ipublic.h
H5Lpublic.h
H5LTpublic.h
H5MMpublic.h
H5Opublic.h
H5overflow.h
H5PLextern.h
H5PLpublic.h
H5Ppublic.h
H5PTpublic.h
H5pubconf.h
H5public.h
H5Rpublic.h
H5Spublic.h
H5TBpublic.h
H5Tpublic.h
H5version.h
H5Zpublic.h
hdf5.h
hdf5_hl.h
klu.h
lapacke_config.h
lapacke.h
lapacke_mangling.h
lapacke_utils.h
ldl.h
metis.h
openblas_config.h
pa_linux_alsa.h
portaudio.h
RBio.h
spqr.hpp
SuiteSparse_config.h
SuiteSparseQR_C.h
SuiteSparseQR_definitions.h
SuiteSparseQR.hpp
umfpack_col_to_triplet.h
umfpack_defaults.h
umfpack_free_numeric.h
umfpack_free_symbolic.h
umfpack_get_determinant.h
umfpack_get_lunz.h
umfpack_get_numeric.h
umfpack_get_symbolic.h
umfpack_global.h
umfpack.h
umfpack_load_numeric.h
umfpack_load_symbolic.h
umfpack_numeric.h
umfpack_qsymbolic.h
umfpack_report_control.h
umfpack_report_info.h
umfpack_report_matrix.h
umfpack_report_numeric.h
umfpack_report_perm.h
umfpack_report_status.h
umfpack_report_symbolic.h
umfpack_report_triplet.h
umfpack_report_vector.h
umfpack_save_numeric.h
umfpack_save_symbolic.h
umfpack_scale.h
umfpack_solve.h
umfpack_symbolic.h
umfpack_tictoc.h
umfpack_timer.h
umfpack_transpose.h
umfpack_triplet_to_col.h
umfpack_wsolve.h
```

**Comment by mtmiller** [comment]
The biggest offenders are going to be binary files, not header files. We can certainly nitpick which include files and examples we can rip out, but it's not going to save much space.

Biggest blobs are
* jre/lib/modules - 158 MB, I don't know what this is, probably important?
* lib/libopenblasp-r0.2.20.a - 63 MB, we shouldn't need to keep static libraries

We should be able to safely delete all lib/*.a for a savings of about 90 MB. While we're at it, delete all lib/*.la and lib/octave/*/*.la. These are tiny text files but most distributions delete them because they often cause more harm than good.

The libqhull_p and libqhull_r libraries should be safe to delete, both shared and static.

SymPy takes up about 40 MB, but I suppose that's important if you want users to be able to use the symbolic package out of the box.

**Comment by mtmiller** [comment]
So that's the following globs

```
lib/lib*.a
lib/lib*.la
lib/libqhull_*
lib/octave/*/lib*.la
```

for a savings of 90 MB.

I think the `jre/lib/modules` file is some packed form of the entire Java runtime, so that needs to stay.

Out of about 500 MB, 90 MB we can safely delete, 184 MB is the Java runtime, 63 MB is Octave itself, 62 MB is supporting math and graphics shared libraries, 44 MB is ghostscript, 40 MB is SymPy, and the leftover 15 MB or so is other utilities and small files.

Is the `lib/debug` directory kept intentionally? That is a total of 34 MB.

**Comment by Alexander-Wilms** [comment]
> The biggest offenders are going to be binary files, not header files. We can certainly nitpick which include files and examples we can rip out, but it's not going to save much space.

Okay, let's keep them

> jre/lib/modules - 158 MB, I don't know what this is, probably important?

No idea. We could simply not copy it from the org.freedesktop.Sdk.Extension.openjdk9 extension and instead instruct people to install it if necessary.

> lib/lib*.a
> lib/lib*.la
> lib/libqhull_*
> lib/octave/*/lib*.la

Added them to the cleanup list.

> Is the lib/debug directory kept intentionally? That is a total of 34 MB.
I think during the submission review of this or another application it was said that this directory should be kept. @TingPing Is that right?

**Comment by TingPing** [comment]
The debug directory isn't in the normal package it gets pulled out into a `.Debug` sub-package.

**Comment by Alexander-Wilms** [comment]
Indeed, it's empty:
```
[awilms@Laptop ~]$ flatpak run --command=sh org.octave.Octave 
sh-4.3$ cd /app/lib/debug
sh-4.3$ ls
sh-4.3$ 
```

**Comment by mtmiller** [comment]
> No idea. We could simply not copy it from the org.freedesktop.Sdk.Extension.openjdk9 extension and instead instruct people to install it if necessary.

I think it's important to keep Java, since several forge packages do depend on the Java calling interface.

**Comment by mtmiller** [comment]
> Indeed, it's empty:

Hmm, maybe I am doing something wrong locally? This is my build, not the build from flathub.

```
mike@galago:~$ flatpak run --command=sh org.octave.Octave 
sh-4.3$ find /app/lib/debug -type f -print | wc -l
805
```

**Comment by Alexander-Wilms** [comment]
Do you have org.octave.Octave.Debug installed?

**Comment by mtmiller** [comment]
No, only org.octave.Octave. There is no Debug package in my local repo.

After `flatpak-builder --force-clean build org.octave.Octave.json` I see debug files in `build/files/lib/debug`, and they show up in the app after `flatpak build-export repo build` and `flatpak update`.

**Comment by Alexander-Wilms** [comment]
I use `flatpak-builder --force-clean --ccache --repo=octave-repo octave-build org.octave.Octave.json` and `flatpak update org.octave.Octave`. I'll try your commands.

**Comment by mtmiller** [comment]
Ok, forget the distraction, `flatpak-builder --repo` must be passing `--exclude=something` to `flatpak build-export`, doesn't matter.

**Comment by mtmiller** [comment]
I think so, closing. I have a couple more local changes I'm about to push that will cut a few MB more, but I think we're a lot better now.

**Comment by RoyiAvital** [comment]
Do you use OpenBLAS for BLAS or the default Ocatve one?

**Comment by RoyiAvital** [comment]
Could anyone answer my question:

> Do you use OpenBLAS for or the default BLAS in this distribution of Ocatve?

**Comment by mtmiller** [comment]
> Could anyone answer my question:

@RoyiAvital You have asked a question which is unrelated and off-topic here, and you're asking it on a closed issue that is over a year old. You will more likely get more helpful and prompt responses if you ask on an appropriate forum, such as the Flatpak or Octave mailing lists or IRC channels.

> > Do you use OpenBLAS for or the default BLAS in this distribution of Ocatve?

OpenBLAS.

```
$ flatpak run org.octave.Octave --eval "version -blas"
ans = OpenBLAS (config: OpenBLAS 0.3.5 NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=48)
```
