### ISSUE TITLE
sshpass not available in Flatpak environment

### ISSUE THREAD

**Issue by NotOnBoard** [flathub/org.octave.Octave#133]
Is it possible to add command line apps to the Flatpak environment, specifically sshpass.

I use sshpass via the Octave system function, to authenticate a file transfer from a remote system.  This works on Octave 5.2 installed from the native package manager (because I installed sshpass as well), but it does not work when I use Octave 6.2 (Flatpak) presumably because the Flatpak environment does not include sshpass.

I'm using Linux Mint 20.1 Cinamon.

Thanks

**Comment by Alexander-Wilms** [comment]
You can still run commands on the host: `system('flatpak-spawn --host sshpass')`

**Comment by NotOnBoard** [comment]
I wasn't aware of that, thank you, that is a good work around.  I'm finding the documentation a bit opaque.

Is there a simple way to check what environment Octave is running in (Flatpak or Native) so I can conditionally call the appropriate sshpass method ?

Longer term it would be desirable I think to be able to add apps to the environment.

Thanks

**Comment by Alexander-Wilms** [comment]
You can check if the file `/.flatpak-info` exists

**Comment by NotOnBoard** [comment]
Thanks
