### ISSUE TITLE
bash redirection error

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#14]
One of my m-scripts makes a system call to evaluate the diff between two files:

`diff -Bb <(sed 's/^[ \t]*//' file1) <(sed 's/^[ \t]*//' file2)`

No mather if I run the script in Octave or in Octave's bash environment, this is the result:

```
diff: /dev/fd/63: No such file or directory
diff: /dev/fd/62: No such file or directory
sed: couldn't flush stdout: Broken pipe
```

In Octave 4.2.1 and in a regular terminal, the actual diff is displayed.

Do you know what could be wrong or missing? Thanks!

**Comment by kupiqu** [comment]
It seems related to the `sed` part because `diff file1 file2` works.

Any idea how to fix the problem?

**Comment by kupiqu** [comment]
Mmm, `sed 's/^[ \t]*//' file1` works just fine too

**Comment by kupiqu** [comment]
Ok, the problem is actually in bash redirection: `<`

**Comment by kupiqu** [comment]
Indeed. Sorry, it's not just redirection. This is an example that fails to me:

```
echo hello > hello.txt
cat <(sed 's/^[ \t]*//' hello.txt)
```

**Comment by kupiqu** [comment]
Mmm, it doesn't seem to be specific of Octave. Same thing happens in kde and gnome platforms

**Comment by mtmiller** [comment]
Works for me

    $ flatpak run --command=bash org.octave.Octave 
    $ echo hello > hello.txt
    $ cat <(sed 's/^[ \t]*//' hello.txt)
    hello

Not sure what's going on with your runtime or containment, but this doesn't seem like an Octave bug.

**Comment by kupiqu** [comment]
Mmm, thanks. Wondering what is wrong with flatpak at my end :(

Yes, I figured out that is not octave specific, but flatpak... Wondering what is wrong with flatpak at my end :(

Thanks for trying to replicate!

**Comment by kupiqu** [comment]
I see. Thank you

**Comment by kupiqu** [comment]
Flatpak 0.11.4 has fixed the issue for me
