### ISSUE TITLE
Installing signal package fails

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#15]
Does config.h not get installed? We only clean up /include/QSci, so I'm wondering why that one header file is missing

Running `pkg install -forge signal` results in
```
/app/include/octave-4.3.0+/octave/../octave/lo-mappers.h:788:12: note: declared here
 inline int NINT (double x) { return octave::math::nint(x); }
            ^~~~
sosfilt.cc:16:27: fatal error: octave/config.h: No suchfile or directory
 #include <octave/config.h>
                           ^
compilation terminated.
```

**Comment by mtmiller** [comment]
This isn't a flatpak bug, the signal 1.3.2 package isn't compatible. I'm working on a new release at this moment.

**Comment by mtmiller** [comment]
ProTip - in Octave 4.4, you can install packages from a URL. So

    `pkg install https://hg.mtmxr.com/octave-signal/archive/tip.tar.gz`

should give you the latest development snapshot. Let me know if that fails to install

**Comment by mtmiller** [comment]
There will probably be other packages that aren't compatible with 4.4 yet, some may have been fixed but not released, some may not be fixed in git/hg yet.

**Comment by Alexander-Wilms** [comment]
Thanks, but either the check needs to be removed or the archive needs to be renamed:

```
>> pkg install https://hg.mtmxr.com/octave-signal/archive/tip.tar.gz
warning: You are installing from an unofficial source.
The GNU Octave community is not responsible for the content of this package.
https://hg.mtmxr.com/octave-signal/archive/tip.tar.gz will be downloaded and installed.
Are you sure you want to do this? (yes or no) yes
package name 'signal' doesn't correspond to its filename 'tip.tar'
error: called from
    install at line 119 column 11
    pkg at line 449 column 9
```

**Comment by mtmiller** [comment]
Already ran into that and removed the check :wink:

**Comment by Alexander-Wilms** [comment]
👍 Alright, I'll download it manually then
