### ISSUE TITLE
use Octave 4.4 official source release

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#16]
The first release candidate for Octave 4.4 is likely being built this week. Once that is up on alpha.gnu.org, we can drop the binary blob tarball in this repo.

**Comment by Alexander-Wilms** [comment]
Could the Flathub page be mentioned [here](https://www.gnu.org/software/octave/#install), then?

**Comment by mtmiller** [comment]
Sure, can we call Flathub a distribution?

**Comment by Alexander-Wilms** [comment]
Hm, not really. May add a sentence like "A cross distribution Flatpak is provided on [Flathub](https://flathub.org/apps/details/org.octave.Octave)"?

**Comment by mtmiller** [comment]
Can you raise this on the bug tracker or the maintainers mailing list? I don't want to make a unilateral change that might appear to elevate Flathub above other distributions without some discussion on the best wording for including it.

**Comment by Alexander-Wilms** [comment]
Yes, done.

**Comment by Alexander-Wilms** [comment]
lzip isn't part of the Sdk, will tar.gz/xz versions be uploaded later?

**Comment by mtmiller** [comment]
How did it work for my local build?

Since 4.2.0 the release candidates have been tar.lz only, the official release will be tar.{gz,lz,xz}.

**Comment by mtmiller** [comment]
Can we add lzip to the manifest just to be able to extract the source? Or would that not work?

If there's absolutely no way around this, I can build a separate copy of octave-4.3.90.tar.xz and host it elsewhere for flatpak to pull from.

**Comment by Alexander-Wilms** [comment]
Yes, that would work. Here's an example where I bundled p7zip: https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony/blob/master/com.realm667.WolfenDoom_Blade_of_Agony.json#L26

By adding "cleanup": ["*"] to the module, it doesn't end up in the final build.

**Comment by mtmiller** [comment]
> Maybe lzip has recently been added to the Freedesktop or KDE Sdk

When I start a shell, I get

```
$ flatpak run --devel --command=bash org.octave.Octave 
$ which lzip
which: no lzip in (...)
$ lzip
bash: lzip: command not found
$ tar -tf octave-4.3.90.tar.lz | head
tar (child): lzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

I have no idea how the build worked for me, unless it's using my host `tar` command to extract.

**Comment by mtmiller** [comment]
> unless it's using my host `tar` command to extract

That might be it, since it failed again after you added lzip.

**Comment by mtmiller** [comment]
So if the extraction happens on the host, outside of the build / runtime environment, can we file an issue somewhere to make sure that all flathub buildbot workers have lzip? After all, shouldn't all buildbot workers support all the file extensions that flatpak-builder supports?

https://github.com/flatpak/flatpak-builder/blob/master/src/builder-source-archive.c#L88

**Comment by Alexander-Wilms** [comment]
Yes, https://github.com/flathub/flathub/issues would be the right place to file the issue.
