### ISSUE TITLE
build with debug symbols?

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#18]
@Alexander-Wilms a while ago you set CFLAGS and CXXFLAGS to explicitly be -O2. This means most modules are compiled without debug symbols. I followed suit and did the same to cmake and qmake modules for consistency.

But flatpak automatically strips out debugging info into a separate Debug layer that a user can optionally install when debugging an error or a crash or something. Do we want to build everything with -g so that is supported? Is there a policy or consensus for flathub builds to support the Debug layer or not?

**Comment by Alexander-Wilms** [comment]
There's been some discussion regarding this here: https://github.com/flathub/flathub/issues/319

If the dependencies' build system enable optimization by default, I think we should remove the global build options as well.

**Comment by mtmiller** [comment]
For future reference, some libraries build with optimization but without debug by default, e.g. openblas and fftw3, and the flatpak position seems to be to follow upstream wishes here.

For all cmake builds, we are explicitly building them with the `RelWithDebInfo` build profile, because cmake projects tend to leave flags empty by default and let the builder decide which profile to use.

Qscintilla2 inherits its flags from Qt qmake defaults, so we will follow however org.kde.Sdk is configured. At the moment, it looks to me like i386 is configured for `release` by default, but x86_64 is configured for `debug` by default.
