### ISSUE TITLE
Desktop file description/comment localization: hu (Hungarian - magyar)

### ISSUE THREAD

**Issue by ovari** [flathub/org.octave.Octave#184]
How can `Interactive programming environment for numerical computations` in the Desktop file be translated?

The Hungarian translation is `Interaktív programozási környezet számszerű számításokhoz`

The image below is with the Flathub version running on the Linux Mint 20.2 Cinnamon operating system.

Thank you

![kép](https://user-images.githubusercontent.com/17465872/133871074-87ed39a0-e583-48cb-aecd-af1b1e515e26.png)

**Comment by mtmiller** [comment]
Hi @ovari, thanks for your suggestion. The best way to help translate this is with a patch to the Octave files org.octave.Octave.desktop.in and org.octave.Octave.appdata.xml, in the directory [etc/icons](https://hg.savannah.gnu.org/hgweb/octave/file/d603f1229301/etc/icons) in the [upstream repository](https://hg.savannah.gnu.org/hgweb/octave).

Are you able to submit a patch file or pull request to add these translations? Are you also able to translate the full description in org.octave.Octave.appdata.xml into Hungarian? Thanks!

**Comment by ovari** [comment]
Sent the strings by email to Rik. Hope it works.

```
Comment=Interactive programming environment for numerical computations
Comment[hu]=Interaktív programozási környezet számszerű számításokhoz
```

**Comment by ovari** [comment]
@mtmiller have updated https://github.com/flathub/org.octave.Octave/issues/184#issuecomment-922440029 so it now contains the `Comment`, `summary` and `description` in Hungarian.

If there is a way to submit them to the repository you mention using a web browser, could you please advise how; otherwise, we are happy if you submit them for Hungarian users to benefit from them.

Thank you

**Comment by mtmiller** [comment]
OK, thank you, there is no web submission form, but I can convert these into a patch on your behalf. Would you like to give your name and email address for credit / acknowledgment for this translation?

**Comment by mtmiller** [comment]
Oh, there is another paragraph in the `description`, would you mind translating that as well? It's weird, but there's a second paragraph in English interleaved after the translations of the first paragraph.

Here's the second paragraph in English for reference:

```text
      Octave has extensive tools for solving common numerical linear algebra
      problems, finding the roots of nonlinear equations, integrating ordinary
      functions, manipulating polynomials, and integrating ordinary
      differential and differential-algebraic equations. It is easily
      extensible and customizable via user-defined functions written in
      Octave's own language, or using dynamically loaded modules written in
      C++, C, Fortran, or other languages.
```

**Comment by ovari** [comment]
```
      Octave has extensive tools for solving common numerical linear algebra
      problems, finding the roots of nonlinear equations, integrating ordinary
      functions, manipulating polynomials, and integrating ordinary
      differential and differential-algebraic equations. It is easily
      extensible and customizable via user-defined functions written in
      Octave's own language, or using dynamically loaded modules written in
      C++, C, Fortran, or other languages.
```

```
      Az Octave kiterjedt eszközökkel rendelkezik a gyakori numerikus lineáris
      algebrai problémák megoldásához, a nemlineáris egyenletek gyökereinek
      megkereséséhez, a hétköznapi függvények integrálásához, a polinomok
      manipulálásához, valamint a közönséges differenciál- és differenciál-
      algebrai egyenletek integrálásához. Könnyen bővíthető és testreszabható
      a felhasználó által meghatározott, Octave saját nyelvén írt funkciókkal,
      vagy dinamikusan betöltött modulokkal, C ++, C, Fortran vagy más
      nyelveken.
```

Sorry for not providing the other paragraph earlier.

**Comment by ovari** [comment]
> OK, thank you, there is no web submission form, but I can convert these into a patch on your behalf.

Thank you

> Would you like to give your name and email address for credit / acknowledgment for this translation?

If you require any future Hungarian translations please advise via:
Óvári ovari123@zoho.com

or GitHub contact
@ovari

Thank you

**Comment by mmuetzel** [comment]
Thanks for these translations. (And to Mike for bringing this to our attention on Octave's [discourse forum](https://octave.discourse.group/t/start-release-process-for-octave-6-4-0/1652/12).)

I pushed a patch with these strings to the upstream repository here:
http://hg.savannah.gnu.org/hgweb/octave/rev/fe2c64849660

@ovari: Afaict, there is currently no Hungarian translation for Octave's GUI. Would you be interested on working on that for Octave 7? If so, please leave a comment here or on the discourse forum.

**Comment by ovari** [comment]
> Thanks for these translations.

You are welcome. Thank you for promptly accepting them.

> I pushed a patch with these strings to the upstream repository here:
http://hg.savannah.gnu.org/hgweb/octave/rev/fe2c64849660

Thank you for providing the link.

> @ovari: Afaict, there is currently no Hungarian translation for Octave's GUI. Would you be interested on working on that for Octave 7? If so, please leave a comment here or on the discourse forum.

Yes, it would be an honor to translation [Octave](https://www.gnu.org/software/octave/)’s GUI into Hungarian.

Do you accept web based translations? For example [Weblate](https://weblate.org/), either [Hosted Weblate](https://hosted.weblate.org/) or your own instance like [Linphone](https://weblate.linphone.org/).

We do not have Discourse; however, we do have [Jami](https://jami.net/) or we could call you if you prefer.

Thank you once again.

**Comment by mmuetzel** [comment]
Thanks for showing interest in translating Octave's GUI to Hungarian.
We don't have any fixed dates yet. But the call for translations for Octave 7 will probably be happening some time in November or December.

Octave's GUI is Qt-based. The best way to translate the strings in the GUI is using Qt Linguist.

Octave's discourse forum is free for anyone to register an account on:
https://octave.discourse.group/
It would probably be best to continue the discussion there. 
If you have any questions on how to setting yourself up for the translation, you'll probably find competent help on that forum.

**Comment by mtmiller** [comment]
Closing as applied. The translation will be part of the next releases of Octave.
