### ISSUE TITLE
Issue with zeromq package

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#19]
I have added a zeromq module to the manifest, but when trying to install the zeromq package, the zmq.h header can't be found.

**Comment by Alexander-Wilms** [comment]
@mtmiller Should I file bugs against all Octave Forge packages I encounter that require uncommon dependencies and ask if they could bundle them?

**Comment by mtmiller** [comment]
I would be open to getting such a bug report if I were the maintainer of a package that depended on an external library. The control package is the only one I can think of that does this.

There's not really a global Octave Forge policy. Packages are supposed to declare system dependencies, but it's basically up to the user to take care of installing those as needed.

**Comment by mtmiller** [comment]
Do you know why the package build fails when the zeromq library is included in the Octave flatpak app manifest? Is the header file not installed on the standard include search path? Does adding `-I/app/include` to the CPPFLAGS environment variable solve this? If so, is there a way we can set that globally?

**Comment by Alexander-Wilms** [comment]
Indeed, setting CPPFLAGS and LDFLAGS helped, thanks.
