### ISSUE TITLE
Allow enabling the JIT compiler flag

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#194]
Could you please allow enabling the JIT compiler flag in the flatpak container? I tried to enable it and this is the message I got:

```
> /var/lib/flatpak/exports/bin/org.octave.Octave --jit-compiler
warning: jit_enable: support for JIT was unavailable or disabled when Octave was built
```

There's a very simple for-loop (single for loop in a simulation) that I'd like to speed up (it takes long time to run the simulation from t_start to t_end) and would like to check it enabling JIT would make it faster, thanks in advance!

**Comment by Alexander-Wilms** [comment]
You can try the test build once it's done

**Comment by Alexander-Wilms** [comment]
JIT is not officially supported and appears to be broken: https://octave.discourse.group/t/which-llvm-should-i-use-for-jit-support/558/2

I added LLVM to the manifest and added the --enable-jit build option, but the build failed: https://flathub.org/builds/#/builders/32/builds/68276

**Comment by kupiqu** [comment]
Thanks for checking this out. Given the situation, JIT arguments should probably be removed from Octave itself, but that's another story...
