### ISSUE TITLE
Compiling a standalone application (w/ the interpreter embedded) from flatpak's octave

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#196]
I may need some help or maybe something is not working in flatpak's Octave as expected, not sure; I'm trying to follow this doc, in particular the embedded example: https://octave.org/doc/v6.4.0/Standalone-Programs.html

However, when I compile (`mkoctfile --link-stand-alone embedded.cc -o embedded`), I get:

```
fatal error: octave/oct.h: File or directory does not exist
    2 | #include <octave/oct.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

This I can workaround by setting the full path in the cc code, but doesn't really look very nice, I guess there must be a better way...:

```
#include </var/lib/flatpak/app/org.octave.Octave/x86_64/stable/080e989716d32b685470ce46006edbb80314bbb56274e99f3a9a8e05743e14eb/files/include/octave-6.4.0/octave/oct.h>
```

But even if I do that, I then get a library error I couldn't workaround:

```
/usr/bin/ld: cannot find -loctinterp
/usr/bin/ld: cannot find -loctave
collect2: error: ld returned 1 exit status
```

I tried giving the location of the libraries with -Lpath_to_lib, but this didn't work either, so I need some help here. It may very well be that there is nothing wrong with flatpak and it's just me that needs a bit of guidance. Thanks in advance

**Comment by Alexander-Wilms** [comment]
The example works for me on a faily new Octave Flatpak installation:

```
#include <iostream>
#include <octave/oct.h>

int
main (void)
{
  std::cout << "Hello Octave world!\n";

  int n = 2;
  Matrix a_matrix = Matrix (n, n);

  for (octave_idx_type i = 0; i < n; i++)
    for (octave_idx_type j = 0; j < n; j++)
      a_matrix(i,j) = (i + 1) * 10 + (j + 1);

  std::cout << a_matrix;

  return 0;
}
```

```
>> mkoctfile --link-stand-alone standalone.cc -o standalone
>> system('flatpak-spawn --host ./standalone');
Hello Octave world!
 11 12
 21 22
```

I didn't have to specify the include or library paths. However, I had to install regular Octave so the binary can find liboctave. Maybe try deleting `~var/app/org.octave.Octave/`?

**Comment by kupiqu** [comment]
I was actually referring to the more sophisticated example called `embedded`, but the main issue was that I was calling mkoctfile in a bash terminal. Once I called mkoctfile in Octave's console, it didn't complain.

However, the standalone executable isn't aware of where the required libraries are, but this is an issue related to Octave more than its flatpak container, I think.

**Comment by kupiqu** [comment]
But checking again the tutorial I linked in the first comment, I see `mkoctfile` being called in the shell... :/

Also the way you do it, works for the standalone example, but it doesn't for the embedded example, it complains about liboctinterp:

```
>> system('flatpak-spawn --host ./embedded');
./embedded: error while loading shared libraries: liboctinterp.so.9: cannot open shared object file: No such file or directory
```

**Comment by kupiqu** [comment]
I tried installing the distro package but didn't work because current Octave version in my system is Octave 5.2, using liboctinterp.so.7:

`error while loading shared libraries: liboctinterp.so.9: cannot open shared object file: No such file or directory`

`ii  liboctave7:amd64                              5.2.0-1                                                       amd64        shared libraries of the GNU Octave language`

And actually that's really the purpose of using flatpak in my case, so I can use latest stable version which is not really available in my system otherwise.

isn't there a way to inform the system where liboctinterp.so.9 from flatpak is?

**Comment by kupiqu** [comment]
Or even better, when creating the executable with mkoctfile from within flatpak's octave, have a "flatpak's" executable (meaning that the executable lives in, or is aware of, flatpak's environment)

**Comment by mtmiller** [comment]
It looks to me like this is working as expected, right? Namely that you can compile a standalone program against Octave, and as long as you run it within the flatpak environment it works as expected?

The remaining comments seem to be more of a question, is there a way to get a standalone executable to load the libraries inside of the flatpak runtime? And I don't think that's generally a good idea, but you could set LD_PRELOAD or LD_LIBRARY_PATH to force it if you really want to try.

The safer way would be something like `flatpak run --command=/path/to/my/program org.octave.Octave`. And just like flatpak creates shim shell scripts to run its programs, you could create your own shim script to run your program this way. Any remaining problems?
