### ISSUE TITLE
Freeze when trying to save .m file

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#2]

**Comment by mtmiller** [comment]
Is this with the code editor? No idea how to debug this. Is this only with flatpak? If not, I would suggest working this upstream with people more familiar with the Qt side of Octave.

**Comment by Alexander-Wilms** [comment]
I'll make a regular Octave build and test it.

**Comment by Alexander-Wilms** [comment]
The issue also occurs with a regular build. I'll try to create a backtrace this week.
