### ISSUE TITLE
flatpak update error: corrupted file

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#20]
```
flatpak update
Looking for updates...
Updating: org.octave.Octave/x86_64/stable from flathub
[####################] Downloading: 17.2 kB/17.2 kB (5.7 kB/s)                 
Error: Failed to update org.octave.Octave/x86_64/stable: While pulling app/org.octave.Octave/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='87b23efa4f916fbb97beb8a23a47d6c5bb1960fea0e8072f972131af1f0b892a' actual='52ad63b7264cf0d74156f655753254862bc65bfc2f17ba20f7da5f1e20965d13'
error: One or more operations failed
```

**Comment by Alexander-Wilms** [comment]
Can't reproduce this here, and that doesn't sound like something a faulty manifest could cause. Is this reproducible for you and have you tried un- and reinstalling it again?

**Comment by kupiqu** [comment]
I have been reproducing it all the time, and wanted to hear sth like what
you said before trying to uninstall.

>
Now I think it will probably reinstall correctly. Will try when I have a
chance and will let you know...

Thanks

**Comment by kupiqu** [comment]
It works, closing...

Thanks
