### ISSUE TITLE
Consider splitting the modules into an independent file to enable other projects to include this one

### ISSUE THREAD

**Issue by travier** [flathub/org.octave.Octave#209]
First, thanks for maintaining Octave on Flathub!

We would like to include support for Octave in Cantor (see https://github.com/flathub/org.kde.cantor/pull/3) but instead of copy/pasting everything, it would be useful for us if we could directly include Octave as a module via a Git sub-module.

For that to work, the Octave manifest should be split with the modules in an other file and the top of the manifest kept as is.

I'll make a PR to make this more concrete.

**Comment by Alexander-Wilms** [comment]
I tried it, but apparently one can only have one module per included file. This would make it hard to keep the overview.

Perhaps this would require a change in `flatpak-builder`.

**Comment by Alexander-Wilms** [comment]
Is there still a demand for this?

**Comment by travier** [comment]
Yes, that would help us including this in https://github.com/flathub/org.kde.cantor
