### ISSUE TITLE
Octave uses the end-of-life org.kde.Sdk//5.15 SDK

### ISSUE THREAD

**Issue by LaurentBonnaud** [flathub/org.octave.Octave#212]
Hi,

here is the problem:
```
$ flatpak update
Looking for updates…
Info: org.kde.Sdk//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.octave.Octave
```

**Comment by cbm755** [comment]
It took me a while to find out the options here in another project.  In case its helpful, I think either:
  - runtime/org.kde.Sdk//5.15-21.08
  - runtime/org.kde.Sdk//6.2
(Probably the first if we're on Qt 5?)

**Comment by kevinsmia1939** [comment]
I send a pr to update the sdk here https://github.com/flathub/org.octave.Octave/pull/217

**Comment by LaurentBonnaud** [comment]
Thanks @mtmiller for the fix!
