### ISSUE TITLE
GNU Octave 7.1.0 Released

### ISSUE THREAD

**Issue by ovari** [flathub/org.octave.Octave#215]
GNU Octave 7.1.0 Released
https://www.gnu.org/software/octave/news/release/2022/04/06/octave-7.1.0-released.html

GNU Octave Version 7
Summary of important user-visible changes
https://www.gnu.org/software/octave/NEWS-7.html

Thank you

**Comment by kevinsmia1939** [comment]
I send a pr here https://github.com/flathub/org.octave.Octave/pull/217

**Comment by mtmiller** [comment]
You don't need to close the issue until the PR is merged, this hasn't been fixed yet.

**Comment by ovari** [comment]
Thank you
