### ISSUE TITLE
Octave 7.1 does not see the list of packages

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#219]
After the update to Octave 7.1, `pkg list` lists nothing, as if no package was previously installed.

**Comment by mtmiller** [comment]
Yes, that's right. A new version of Octave has a new library API and in general all packages need to be recompiled / reinstalled, and the package prefix includes the version number to reflect that.

Just like upgrading Python 3.9 to 3.10, all packages need to be reinstalled.
