### ISSUE TITLE
Selected text in editor disappears when clicking anywhere outside the editor

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#22]
This is on KDE under Wayland. I'll try it under X later.

**Comment by mtmiller** [comment]
Text disappears or selection is no longer highlighted?

I don't see this with GNOME Wayland. Text remains selected in the editor even when selecting text in the command window or history table.

**Comment by Alexander-Wilms** [comment]
The text disappears. This doesn't occur when running KDE under X either.

**Comment by kupiqu** [comment]
I can confirm that this doesn't happen in X. I will check it out in wayland and will let you know...

**Comment by kupiqu** [comment]
Wow, I can confirm this. I have to say I didn't understand what "disappears" means in this context. I thought that the selection was lost, but this is much worse, the selection is deleted, i.e., the content of the selection vanishes.

**Comment by Alexander-Wilms** [comment]
The OpenSCAD Flatpak uses QScintilla as well, and there the issue doesn't occur: https://github.com/flathub/org.openscad.OpenSCAD/blob/master/org.openscad.OpenSCAD.json#L120

**Comment by kupiqu** [comment]
How do you know it doesn't happen, did you try yourself? 

I wonder what makes the difference... Is openSCAD using Qt5 QScintilla?

**Comment by Alexander-Wilms** [comment]
Yes, I tried it and OpenSCAD uses the 5.11 SDK as well.

**Comment by Alexander-Wilms** [comment]
OpenSCAD doesn't have the Wayland permission set by default. I'm able to reproduce this bug when running it like this: `flatpak run --socket=wayland org.openscad.OpenSCAD`

**Comment by kupiqu** [comment]
So the issue happens with the flatpak+wayland+kde+qscintilla combo. Did we check if this happens when we eliminate flatpak from the equaton?

**Comment by kupiqu** [comment]
ok, it seems it's not a flatpak issue. I can reproduce it with KDE+Wayland+Qscintilla: e.g. octave 4.2.2 from Ubuntu's repos

**Comment by Alexander-Wilms** [comment]
Can you reproduce this with non-flatpak'd OpenSCAD as well? Since it's a smaller project, this would make it easier for upstream to try it for themselves.

Bugs can be reported here: https://www.riverbankcomputing.com/mailman/listinfo/qscintilla

Do you want to report it? Or I can try reproducing it with Octave from the Fedora repos and report it afterwards.

**Comment by kupiqu** [comment]
I reproduced the same thing with OpenSCAD installing it from their launchpad repo (that is, no flatpak involved).

I think I'd prefer if you can report the issue upstream. You will probably summarize the technical details of the issue better and, given that you're involved in the equation as a flatpak packager, they will probably consider your feedback as more reliable.

**Comment by Alexander-Wilms** [comment]
Okay, will do

**Comment by kupiqu** [comment]
Thank u

**Comment by kupiqu** [comment]
when you do, could you please add the link to it, here?

**Comment by Alexander-Wilms** [comment]
Mh, my mail doesn't appear in the archive and it didn't seem to have bounced.
