### ISSUE TITLE
Provide gfortran compiler

### ISSUE THREAD

**Issue by wjt** [flathub/org.octave.Octave#3]
An Endless OS user [reported](http://community.endlessos.com/t/gnu-octave-package-installation-error/4939/6) that when they tried to use `pkg` to install a package from Octave Forge, it failed with the following error:

```
>> pkg install -forge control
sh: gfortran: command not found
make: *** [Makefile:33: slicotlibrary.a] Error 127
make: Entering directory '/tmp/oct-8EfZum/control/src'
tar -xzf slicot.tar.gz
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp; /app/bin/mkoctfile-4.3.0+ -c *.f
make: Leaving directory '/tmp/oct-8EfZum/control/src'

pkg: error running `make' for the control package.
error: called from
    configure_make at line 95 column 9
    install at line 192 column 7
    pkg at line 394 column 9
```

They were trying to install this package to use the `tf` function:

```
>> tf
warning: the 'tf' function belongs to the control package from Octave Forge which
seems to not be installed in your system.

Please read <http://www.octave.org/missing.html> to learn how you can
contribute missing functionality.
error: 'tf' undefined near line 1 column 1
```

I see that the Octave Flatpak already specifies the KDE SDK as its runtime, presumably so that `gcc` is available, but unfortunately `gfortran` is not part of the SDK.

**Comment by nedrichards** [comment]
`gfortran` is absolutely included in the flatpak (it comes from the gfortran FDo SDK extension, and the KDE SDK inherits from FDo):

```
nick@endless-nedr:~/Projects/stencyl-flatpak$ flatpak run --command=bash org.octave.Octave
nick@endless-nedr:~/Projects/stencyl-flatpak$ gfortran 
gfortran: fatal error: no input files
compilation terminated.
```
I was able to run `pkg install -forge control` on Endless OS 3.3.5 using the latest version of Octave and everything worked fine (took a while to compile, mind).

**Comment by wjt** [comment]
That's interesting because the transcripts above are from me reproducing the problem on a machine running Fedora 27 (to check it's not an Endless-specific problem). I installed Octave from GNOME Software.

```console
[wjt@gelf ~]$ flatpak run --command=bash org.octave.Octave
bash-4.3$ gfortran
bash: gfortran: command not found
```

I do not have the GFortran SDK extension installed. It's true that I get this funky error in GNOME Software…

![screenshot from 2017-12-11 19-38-01](https://user-images.githubusercontent.com/86760/33850152-d711e320-deaa-11e7-8a40-470b6a858f91.png)

**Comment by wjt** [comment]
I uninstalled Octave and the KDE SDK from the command line, restarted Software, and re-installed Octave. though Software. It was visibly successful this time, but I still don't have the GFortran SDK extension AFAICT.

**Comment by nedrichards** [comment]
Yeah, you *shouldn't* need it - that's the point of the install.sh bit, in the manifest, it copies the bits you need into the app.

**Comment by Alexander-Wilms** [comment]
Can the issue be closed?

**Comment by wjt** [comment]
Neither GNOME Software nor `flatpak install flathub org.octave.Octave` causes `org.freedesktop.Sdk.Extension.gfortran-62` to be installed, and `gfortran` is not present inside the Octave Flatpak:

```console
$ flatpak run --command=bash org.octave.Octave 
ldconfig: /app/lib/libgfortran.so.3 is not a symbolic link
ldconfig: /app/lib/libquadmath.so.0 is not a symbolic link
bash-4.3$ ls -l /app/lib/libgfortran.so*
lrwxrwxrwx 1 nfsnobody nfsnobody      25 Dec 22 11:21 /app/lib/libgfortran.so -> /app/lib/libgfortran.so.3
-rwxr-xr-x 2 nfsnobody nfsnobody 1206304 Jan  1  1970 /app/lib/libgfortran.so.3
-rwxr-xr-x 2 nfsnobody nfsnobody 1206312 Jan  1  1970 /app/lib/libgfortran.so.3.0.0
bash-4.3$ find /usr /app -name gfortran
bash-4.3$ exit
```

(The warnings from `ldconfig` only appear on first launch.)

It is not surprising that the `gfortran` _executable_ is not included in the flatpak because nothing copies it in. The Flatpak manifest runs `/usr/lib/sdk/gfortran-62/install.sh` and `ln -s /app/lib/libgfortran.so.3 /app/lib/libgfortran.so`; the former looks like this:

```console
% flatpak install flathub org.freedesktop.Sdk.Extension.gfortran-62
Installing: org.freedesktop.Sdk.Extension.gfortran-62/x86_64/1.6 from flathub
[####################] 1 delta parts, 14 loose fetched; 124521 KiB transferred in 58 seconds
% flatpak run org.freedesktop.Sdk/x86_64/1.6
sh-4.3$ cat /usr/lib/sdk/gfortran-62/install.sh 
#!/bin/sh
mkdir -p /app/lib
cp /usr/lib/sdk/gfortran-62/lib/libquadmath.so* /usr/lib/sdk/gfortran-62/lib/libgfortran.so.3* /app/lib/
```

Should the Octave flatpak just depend on the gfortran SDK extension at runtime?

**Comment by wjt** [comment]
It's either that, or copy more stuff from the SDK extension to the app, or require users to divine that `sh: gfortran: command not found` means “run `flatpak install flathub org.freedesktop.Sdk.Extension.gfortran-62` in a terminal" :-)

**Comment by Alexander-Wilms** [comment]
Hm, I thought the install.sh scripts of the OpenJDK and gfortran extensions were meant to copy everything. 'java' and 'javac' don't work either if the OpenJDK extension is not installed. I don't know how to make the extensions a runtime dependency, though. Especially since I'm using the KDE Sdk as runtime.

**Comment by mtmiller** [comment]
I can confirm, in case there was any doubt

```
$ flatpak run --command=octave org.octave.Octave --eval "system 'which gfortran';"
/usr/lib/sdk/gfortran-62/bin/gfortran
$ flatpak uninstall org.freedesktop.Sdk.Extension.gfortran-62/x86_64/1.6
Uninstalling: org.freedesktop.Sdk.Extension.gfortran-62/x86_64/1.6
$ flatpak run --command=octave org.octave.Octave --eval "system 'which gfortran';"
which: no gfortran in (/app/bin:/usr/bin:/usr/lib/sdk/gfortran-62/bin:/usr/lib/sdk/openjdk9/bin:/app/libexec/octave/4.3.0+/site/exec/x86_64-pc-linux-gnu:/app/libexec/octave/api-v51+/site/exec/x86_64-pc-linux-gnu:/app/libexec/octave/site/exec/x86_64-pc-linux-gnu:/app/libexec/octave/4.3.0+/exec/x86_64-pc-linux-gnu:/app/bin)
$ flatpak install gnome org.freedesktop.Sdk.Extension.gfortran-62/x86_64/1.6
Installing for user: org.freedesktop.Sdk.Extension.gfortran-62/x86_64/1.6 from gnome
[####################] 1 delta parts, 13 loose fetched; 124062 KiB transferred in 55 seconds
$ flatpak run --command=octave org.octave.Octave --eval "system 'which gfortran';"
/usr/lib/sdk/gfortran-62/bin/gfortran
```

I agree we need a way to declare a dependency on the extension at runtime, I don't think we want to copy the entire contents of gfortran into the Octave app bundle.

**Comment by Alexander-Wilms** [comment]
@alexlarsson Can you give us some insight?
