### ISSUE TITLE
Print latex not working

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#31]
I tried the following example after a thread in octave help mailing list (from manual https://octave.org/doc/v4.4.1/Printing-and-Saving-Plots.html):

```
x = 0:0.01:3;
hf = figure ();
plot (x, erf (x));
hold on;
plot (x, x, "r");
axis ([0, 3, 0, 1]);
text (0.65, 0.6175, ['$\displaystyle\leftarrow x = {2 \over \sqrt{\pi}}'...
                     '\int_{0}^{x} e^{-t^2} dt = 0.6175$'],
      "interpreter", "latex");
xlabel ("x");
ylabel ("erf (x)");
title ("erf (x) with text annotation");
print (hf, "plot15_7.pdf", "-dpdflatexstandalone");
```

There is no error in flatpak's Octave but there is no text printed  at all, I guess because system's pdflatex is not found.

**Comment by mtmiller** [comment]
Do you mean that you get a plot figure in the pdf file with no text printed in it? That is the correct behavior. The point of this command is to generate a pdf of the plot and an accompanying .tex file that contains the labels and markup, which together can be included or processed by a TeX command outside of Octave.

**Comment by mtmiller** [comment]
IOW, you the user are supposed to run pdflatex on the output file `plot15_7.tex`, or include it in some larger document.

**Comment by kupiqu** [comment]
Ok, I missed that part. Then this is correct behavior.

But, what if I want to have an octave figure with latex symbols in it. Does it work, or do I need to do it externally?

**Comment by mtmiller** [comment]
There is a subset of LaTeX symbols that Matlab supports and Octave also supports, possibly only for certain file types, I can't remember the details. I think the standalone targets are for full LaTeX support.

**Comment by kupiqu** [comment]
Ok, sorry for the noise
