### ISSUE TITLE
Octave won't launch GUI following runtime update to 6.6

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.octave.Octave#316]
Following the update of Octave's underlying runtime to 6.6, the GUI will no longer launch.

Environment:
OS: openSUSE Aeon
Desktop: GNOME
Session type: Wayland

**Comment by Alexander-Wilms** [comment]
Thanks for the report, I'll revert it for now and investigate: https://github.com/flathub/org.octave.Octave/pull/318

**Comment by neildarlow** [comment]
Hi,

Not sure if this is like I discovered for the UltiMaker Cura flatpak where removing of the qmlcache directory contents fixed the issue.

**Comment by Alexander-Wilms** [comment]
I don't think Octave uses QML.
