### ISSUE TITLE
Flatpak will not load GUI on Linux Mint

### ISSUE THREAD

**Issue by chetWS** [flathub/org.octave.Octave#337]
I'm trying to run Octave 9.1.0 Flatpak on Linux Mint Mate, but I cannot get the gui app to run.

The shortcut that's set up by Mint's software manager executes this command:

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/octave --file-forwarding org.octave.Octave --gui @@ %f @@`

Nothing happens when I click the shortcut.  No error message pops up.  Nothing.

When I type `flatpack run org.octave.Octave` on the command line, I get Octave's command prompt shown in the screenshot which appears to work OK. There is a funny error message, however.

![image](https://github.com/flathub/org.octave.Octave/assets/111878169/adfbb53f-002c-46a9-ae7b-03240e1528e9)

When I type `flatpack run org.octave.Octave --gui` on the command line, I get the following:

![image](https://github.com/flathub/org.octave.Octave/assets/111878169/83dc7504-bf53-4abc-b58c-32916ab98046)

Perhaps it's having an issue with Qt or gtk3?  I thought flatpaks have everything they need to run a given app correctly?

# My system
- OS:  Linux Mint 21.3 Virginia 64-bit, Kernel Linux 5.15.0-101-generic x86_64, MATE 1.26.0
- Octave version: 9.1.0
- Installation method: Flatpak through Mint's Software Manager

**Comment by Alexander-Wilms** [comment]
The network socket error message is normal, ut the xapp-gtk3-module error message I haven't seen before.

I can't debug this right now, but you can use the 8.4 build available here: https://github.com/flathub/org.octave.Octave/pull/338

**Comment by Alexander-Wilms** [comment]
The `**stack smashing detected**` indicates that it's not a Qt error:

https://stackoverflow.com/questions/61115393/stack-smashing-detected-unknown-terminated-aborted-core-dumped-erro

I can't reproduce this either. Have you tried uninstalling and reinstalling it?

**Comment by Alexander-Wilms** [comment]
This appears to have been caused by org.freedesktop.Platform.GL.nvidia and should be resolved:

https://forums.linuxmint.com/viewtopic.php?t=420345
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1676#note_2002522453
