### ISSUE TITLE
Package Octave Latest to ease pre-release testing (of both source code and packaging itself)

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#34]
In general, having an easy to install and self-contained flatpak package of the latest pre-release Octave version would allow efficient testing and debugging (both of the source code and of the package itself) in production systems for users that aim to help but lack the time and/or the skills to compile octave from source themselves.

In particular with respect to https://savannah.gnu.org/bugs/?54607 (Native KDE open/save dialogs have been reestablished, but a tester is having troubles with it; no more testers have tried this in KDE production systems), I, and maybe other KDE users, would be able to test and help to infer if that issue is general in KDE systems (or rather particular of a given KDE system). This, I hope, will help to identify how broad might the issue be, as well as its potential root cause.

**Comment by TingPing** [comment]
> I don't know if Flathub allows or normally does multiple branches of an application. If so, then we could have a stable and a development build on Flathub. If not, then this would have to be done elsewhere.

Not currently.

**Comment by kupiqu** [comment]
> > I don't know if Flathub allows or normally does multiple branches of an application. If so, then we could have a stable and a development build on Flathub. If not, then this would have to be done elsewhere.
> 
> Not currently.

but, couldn't a branch of this repo be created for packaging octave dev? or that would not be appropriate?

**Comment by mtmiller** [comment]
This project is solely for building Octave for Flathub. If Flathub doesn't support multiple branches or build profiles, which is what I expected, then IMHO this issue isn't appropriate here.

Like I said, I'd be happy to adapt the packaging here into octave-snapshot and publish a nightly build from the development branch for testing purposes.

I recommend we move this to https://github.com/mtmiller/octave-snapshot/issues/17.

**Comment by kupiqu** [comment]
Sounds good, thanks
