### ISSUE TITLE
Octave flatpak package exports an empty or missing AppName

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#35]
In contrast to deb packages in Ubuntu, the Octave GUI from the flatpak package does not export `GNU Octave` as its `AppName` (as far as I can see, the `AppName` is empty or missing).

This is relevant for linux panels displaying the `AppName` of active windows side by side with the global menu, to help identify which application the global menu corresponds to.

Curiously, figures are not affected and properly display `GNU Octave` as their `AppName`.

**Comment by mtmiller** [comment]
Can you explain where exactly the application name is missing? Is this KDE? Is this Wayland or X? Is this a Flatpak packaging issue or a thing missing in upstream Octave?

I see no differences or problems when running Octave natively or via flatpak on my GNOME+Wayland desktop environment. The application is correctly identified as "org.octave.Octave" and the name is correctly set to "GNU Octave".

**Comment by kupiqu** [comment]
> Can you explain where exactly the application name is missing?

I am talking about the AppName, which is displayed in panels (similar to OSX and Linux shells: Unity, GNOME, Plasma) to show the name of the active application.

> Is this KDE? Is this Wayland or X? 

This is in Plasma (KDE's shell) running on top of X11, but would be highly surprised if this is any different in Wayland (will test), or GNOME.

> Is this a Flatpak packaging issue or a thing missing in upstream Octave?

As far as I can see (i.e. compared to deb packages in Ubuntu), it is a flatpak issue. I don't compile octave myself, so I don't know if Ubuntu fixes the upstream issue in Octave, but would be surprise if they do. I think I can try with the packages that you made, which I assume do not deviate from upstream and will report...

> I see no differences or problems when running Octave natively or via flatpak on my GNOME+Wayland desktop environment. The application is correctly identified as "org.octave.Octave" and the name is correctly set to "GNU Octave".

Where is it displayed? I am not referring to the window title, neither the identification properties of the window. I am talking about the AppName that is exported by the application, which is used by panels to display the application name.

**Comment by mtmiller** [comment]
> Where is it displayed?

That's what I would ask too :smile: I'm not sure what you mean by "the AppName that is exported by the application" in the context of your desktop environment.

What I see in GNOME+Wayland is, the window title says "Octave", the global application menu says "GNU Octave", the wmclass property is "GNU Octave", and the org.octave.Octave.desktop menu item is associated with the active window.

If it's a Flatpak issue only, then is this maybe yet another dbus interface that needs to be exposed for an application to properly register itself with KDE?

**Comment by kupiqu** [comment]
Mmm, let's close this: I tested with a new user in X11 and it behaves correctly. Unfortunately, I don't see yet why it doesn't for my user. I tried playing with config files (moving them out so it starts the application anew) for the case this was the issue, but nothing. And it only fails in Octave, so it's not sth about flatpak per se. I'm out of ideas... will try to figure this out tomorrow. If I find the cause I may add it here for the case somebody else encounters the issue.

> ... the global application menu says "GNU Octave", ...

That's the one I was referring to.

**Comment by kupiqu** [comment]
Most likely it won't be this,  but I wonder if the issue may come from having `runtime=org.kde.Sdk/x86_64/5.11` instead of `runtime=org.kde.Platform/x86_64/5.11`

As far as I could see all gnome and kde flatpak applications refer to platform for the runtime instead of to sdk, the latter appearing in the sdk section.

Is there a way to test this without rebuilding the flatpak package?

Another difference with respect to other applications is that I don't see a Locale package referenced in the built-extensions.

I wonder if the issue emerges when any of the two previous differences combines with a different from default locale, which is my case.

**Comment by kupiqu** [comment]
Mmm, I see that manifest.json is the same in org.kde.Sdk and in org.kde.Platform
