### ISSUE TITLE
Update to version 5.0

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#38]
We should create a branch to test the update to Octave 5.0 (and KDE SDK 5.12).

@mtmiller Should we host a current snapshot of the source code in a separate repo, since the hgweb link isn't stable?

**Comment by kupiqu** [comment]
Excellent, I look forward! 

This will allow me to work on the Catalan translations https://savannah.gnu.org/bugs/?55279#comment15

**Comment by mtmiller** [comment]
If you want to build a current snapshot, I regularly upload source archives of 5.0.1 and 6.0.0 to my S3 bucket. For example https://s3.amazonaws.com/octave-snapshot/public/octave-5.0.1.tar.xz.

But the checksum will change since this is a rolling snapshot with the version number unchanging. I'm not sure how you would plan to deal with that.

The first release candidate will be tagged and uploaded to alpha.gnu.org as usual when it's ready.

**Comment by mtmiller** [comment]
I guess if you need something stable I can upload a copy of a particular hg commit ID with a different name, e.g. octave-5.0.1+bdf03ab385c2.tar.xz, that won't be overwritten.

**Comment by Alexander-Wilms** [comment]
Yes, having a particular commit available for testing would be useful.

**Comment by Alexander-Wilms** [comment]
Thanks. What version of Sundials is supported by Octave 5.0?

**Comment by Alexander-Wilms** [comment]
I've updated the manifest: https://github.com/flathub/org.octave.Octave/tree/octave5

Building it now.

**Comment by Alexander-Wilms** [comment]
There's some issue with Qt 5.12:

```
checking Qt version 5... checking for Qt5Core Qt5Gui Qt5Network Qt5PrintSupport Qt5Help Qt5Xml... yes
checking for qtchooser... no
checking for moc-qt5... no
checking for moc... moc
checking for uic-qt5... no
checking for uic... uic
checking for rcc-qt5... no
checking for rcc... rcc
checking for lrelease-qt5... no
checking for lrelease... lrelease
checking for qcollectiongenerator-qt5... no
checking for qcollectiongenerator... no
checking for qhelpgenerator-qt5... no
checking for qhelpgenerator... qhelpgenerator
configure: WARNING: Your installation of Qt version 5 appears incomplete or broken in some way.  Fix that or use --with-qt=VER to use another version.
configure: WARNING: one or more of the Qt utilities moc, uic, rcc, lrelease, qcollectiongenerator, and qhelpgenerator not found; disabling Qt GUI
[...]
  Qt CPPFLAGS:                   -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtNetwork -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtHelp -I/usr/include/QtSql -I/usr/include/QtXml 
  Qt LDFLAGS:                    
  Qt GUI libraries:              -lQt5Network -lQt5PrintSupport -lQt5Help -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Xml -lQt5Core 
  Qt OpenGL libraries:           -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core 
  Qt moc:                        moc 
  Qt uic:                        uic 
  Qt rcc:                        rcc 
  Qt lrelease:                   lrelease 
  Qt qcollectiongenerator:        
  Qt qhelpgenerator:             qhelpgenerator 
```

**Comment by mtmiller** [comment]
Known issue https://savannah.gnu.org/bugs/?55187

You can set QCOLLECTIONGENERATOR in the environment as a workaround.

**Comment by kupiqu** [comment]
Is there a flatpak version of Octave 5 ready to be tested?

**Comment by Alexander-Wilms** [comment]
You can build it locally with the manifest in the octave5 branch. The CI build failed, but I don't know why yet. 

When I ran __run_test_suite__, Octave exited with a signal 6.

**Comment by kupiqu** [comment]
> You can build it locally with the manifest in the octave5 branch.

I did this once some time ago, but I forgot :( I think there was an issue where you told me how to do this, I'll need to explore a bit...

> The CI build failed, but I don't know why yet.

Does it mean I won't be able to test Octave 5, or this fails for a specific test but would be able to launch Octave nevertheless?

**Comment by Alexander-Wilms** [comment]
The command is `flatpak-builder --force-clean --ccache --repo=octave-repo octave-build org.octave.Octave.yaml`

**Comment by kupiqu** [comment]
Excellent, thank you!

**Comment by kupiqu** [comment]
I guess I miss sth, I get the following error:

(flatpak-builder:24077): flatpak-builder-ERROR **: 14:15:40.355: Failed to load included manifest (org.octave.Octave/shared-modules/glu/glu-9.0.0.json): Failed to open file “org.octave.Octave/shared-modules/glu/glu-9.0.0.json”

**Comment by kupiqu** [comment]
mmm weird, that folder is empty in my cloned repo

**Comment by kupiqu** [comment]
I guess I missed about `--recurse-submodules`, will try to clone again

**Comment by Alexander-Wilms** [comment]
Yes, that's the same Error.

**Comment by mtmiller** [comment]
This is what Octave should do (nothing new here, has worked for several releases)

    >> 10^complex(NaN, 1)
    ans =  NaN + NaNi

And this is what happens in the 5.0.1 flatpak build

    >> 10^complex(NaN, 1)
    /usr/include/c++/8.2.0/complex:692: std::complex<_Tp> std::polar(const _Tp&, const _Tp&) [with _Tp = double]: Assertion '__rho >= 0' failed.
    fatal: caught signal Aborted -- stopping myself...

Looks to me like this is revealing a problem somewhere else rather than in Octave itself, but needs more digging to find out exactly where it's diverging.

**Comment by Alexander-Wilms** [comment]
We could try building it with the 5.11 SDK to narrow it down.

**Comment by Alexander-Wilms** [comment]
I built Octave 5.0.1with KDE Sdk 5.11 and OpenJDK 10 and didn't encounter the crash when running the test suite:

```
Summary:

  PASS                            15506
  FAIL                                3
  XFAIL (reported bug)               24
  SKIP (missing feature)             37
  SKIP (run-time condition)          12
```

**Comment by Alexander-Wilms** [comment]
Nice find. I found this: https://gitlab.com/search?utf8=%E2%9C%93&search=D_GLIBCXX_ASSERTIONS&group_id=&project_id=4339844&search_code=true&repository_ref=18.08

I don't know if it's possible to unset single CXXFLAGS, so I guess we need to copy all the flags from the link above except for that one.

**Comment by mtmiller** [comment]
I also filed this to Octave: https://savannah.gnu.org/bugs/?55547

We can probably fix this in Octave 6, but not for the in-progress Octave 5 release.

**Comment by mtmiller** [comment]
For the record, the following options are what I'm seeing in the build log

```
ac_cv_env_CFLAGS_value='-march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
```

which agrees with the lines you found in freedesktop-sdk project.conf:

```
  common_flags: "-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches"
  flags_x86_64: "-march=x86-64 -mtune=generic %{common_flags} -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection"
```

**Comment by mtmiller** [comment]
This is done with 4e9d0b1e0ea2f995c241700d43b4f49fb6d93dc1.
