### ISSUE TITLE
Skip building GraphBLAS, other optional components?

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#40]
I noticed with recent SuiteSparse updates that building the GraphBLAS subdirectory takes a large part of the overall build time now. Skipping this directory would help keep build time and app size down due to a library that Octave doesn't use.

There may be other optional parts of the dependencies that we can skip, but GraphBLAS looks like the major offender at this point.

**Comment by mtmiller** [comment]
I was thinking a patch like this https://salsa.debian.org/science-team/suitesparse/blob/master/debian/patches/mongoose-build.patch

**Comment by Alexander-Wilms** [comment]
Alright. Since Mongoose is a new addition to SuiteSpaarse as well, can it be omitted, too?

**Comment by mtmiller** [comment]
Yeah, Mongoose is new in version 5.4.0 and isn't needed by Octave.

Other suitesparse libraries not used by Octave are LDL, RBIO, and SPQR, but these are tiny compared to GraphBLAS. We could patch out all 5 together.

**Comment by mtmiller** [comment]
This saves about 1.5 hours on the flathub buildbot, compare [this log](http://repo-test.flathub.org:8010/#/builders/6/builds/1558) with [this one](http://repo-test.flathub.org:8010/#/builders/6/builds/1562).
