### ISSUE TITLE
Provide version 4.4.1 and 5 instead of just the version 5 

### ISSUE THREAD

**Issue by lexknuther** [flathub/org.octave.Octave#47]
Many octave packages like signal are not compatible with the Octave 5 RC.  It would be great to have 2 versions of this flatpak instead of just the most recent.

**Comment by mtmiller** [comment]
I don't think the Flathub repository allows for maintaining multiple branches or versions of an application. I'm not a Flathub expert so I'll wait for someone more knowledgeable in the infrastructure to confirm.

That said, this repository is just a recipe. It is very easy for a user to clone this repository and build any new or old version of Octave that they want to use on their own system. The master branch will continue to follow and build only the latest official release of Octave.

**Comment by mtmiller** [comment]
From https://github.com/flathub/flathub/wiki/App-Requirements

> Flathub always builds in the flatpak branchname `"stable"` and it always passes
> `--default-branch=stable`. This means that a branch key doesn't need to be specified.
> If one is specified, it should be `"stable"`.

So to me that confirms that Flathub only hosts the latest version of a particular application. Offering more than one version of Octave would be against Flathub repository policy.

**Comment by barthalion** [comment]
Support for beta channel is being worked on.

**Comment by mtmiller** [comment]
@barthalion Thanks, can you provide a reference to that work in progress?

**Comment by mariomie** [comment]
I was also wondering about the octave version 5. You are referencing the flathub app-requirements that say "Flathub only hosts stable application releases". The current stable version of octave is 4.4.1. So this version should be on flathub.

**Comment by mtmiller** [comment]
@mariomie That's a good point, in the future we should avoid merging release candidates onto the master branch. We have what we have for now, Octave 5.1 will be released soon and there won't be a problem. But for future release candidates we should only test them on feature branches.
