### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#5]
I get the following error:

The info file
/app/share/info/octave.info
or compressed versions do not exist

**Comment by Alexander-Wilms** [comment]
There was an issue with `makeinfo`, which is wy the Flatpak doesn't contain the documentation. Not sure how hard it would be to fix that.

**Comment by kupiqu** [comment]
Thanks for the info. I hope this can be fixed somehow in the near future (hopefully by the time Octave 4.4 is released).

**Comment by mtmiller** [comment]
I believe the intent for 4.4 is to try to build a Qt help file format and use a Qt help browser widget for the GUI, leaving the GNU info format for command-line mode. That is a work in progress over the last week or so.

**Comment by kupiqu** [comment]
I see, that's interesting!

So Mike, do you think this issue is also upstream, then?

**Comment by mtmiller** [comment]
It's upstream as long as we get that resolved!

It's a flatpak issue in that the plaintext info browser does work for me as-is in a non-flatpak build of Octave. So let's leave this open in case we do need to address that. I'll be building this regularly over the coming days and trying to repro some of these issues, and keep an eye on the upstream GUI development tasks.

**Comment by mtmiller** [comment]
Link to [upstream issue](https://savannah.gnu.org/bugs/?53006) working on help widget.

**Comment by mtmiller** [comment]
Link to [upstream issue](https://savannah.gnu.org/bugs/?53430) just filed on failure to install user manual in Info format.

**Comment by mtmiller** [comment]
I will try to look into adding an updated version of GNU Texinfo to the build as a workaround in case the GUI doc browser stays the way it is and needs the info files installed.

**Comment by kupiqu** [comment]
I see. I wonder, couldn't the flatpak package be linked to texinfo 6.1 instead?

**Comment by kupiqu** [comment]
> I will try to look into adding an updated version of GNU Texinfo to the build as a workaround in case the GUI doc browser stays the way it is and needs the info files installed.

Great! if you do that, would it be very hard to updated as well Octave version to current stable? It would allow me to further test issue #7

**Comment by mtmiller** [comment]
I only have enough bandwidth at the moment to test and rebuild with the rolling stable release myself. @Alexander-Wilms is taking care of the builds, and I have no idea how or when they are pushed to the flathub repo for public consumption.

**Comment by Alexander-Wilms** [comment]
I could merge the 4.4 and we could continue work on the master branch.

**Comment by mtmiller** [comment]
I'm ok with whatever you think works best, I'm ignorant of the automation and how the branch name affects builds and the flathub repo.

Just let me know where to push or whether I should start using feature branches and PRs, whatever workflow you want to use.

**Comment by Alexander-Wilms** [comment]
Since we're currently not building a stable release anyway, there's currently no advantage to use feature branches. Just push t master after you've tested a change locally. Once 4.4 is released, we should use feature branches and build on x86 before merging them, though.

**Comment by kupiqu** [comment]
Nice!
