### ISSUE TITLE
Loading signal package produces errors

### ISSUE THREAD

**Issue by stillpointx** [flathub/org.octave.Octave#52]
I did a pkg install -forge signal  and several errors come up now
upfirdn.cc:24:10: fatal error: octave/gripes.h: No such file or directory
 #include <octave/gripes.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:43: upfirdn.oct] Error 1
make: *** Waiting for unfinished jobs....
sosfilt.cc:24:10: fatal error: octave/gripes.h: No such file or directory
 #include <octave/gripes.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:43: sosfilt.oct] Error 1
cl2bp.cc: In function ‘octave_value_list Fcl2bp(const octave_value_list&, int)’:
cl2bp.cc:92:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(0));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:92:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(0));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:97:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(1));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:97:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(1));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:102:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(2));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:102:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(2));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:107:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(3));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:107:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(3));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:112:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(4));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:112:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(4));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:129:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(5));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:129:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(5));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
medfilt1.cc: In function ‘octave_value_list Fmedfilt1(const octave_value_list&, int)’:
medfilt1.cc:362:22: warning: format ‘%d’ expects argument of type ‘int’,but argument 2 has type ‘octave_idx_type’ {aka ‘long int’} [-Wformat=]
               error ("medfilt1: DIM must be positive, not %d", dim);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
remez.cc: In function ‘octave_value_list Fremez(const octave_value_list&, int)’:
remez.cc:792:17: error: ‘NINT’ was not declared in this scope
   int numtaps = NINT (args(0).double_value()) + 1; // #coeff = filter order+1
                 ^~~~
remez.cc:792:17: note: suggested alternative: ‘NAN’
   int numtaps = NINT (args(0).double_value()) + 1; // #coeff = filter order+1
                 ^~~~
                 NAN
make: *** [Makefile:40: cl2bp.o] Error 1
make: *** [Makefile:43: remez.oct] Error 1
make: Entering directory '/tmp/oct-PGQolD/signal-1.4.0/src'
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  __fwht__.cc-o __fwht__.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  __ultrwin__.cc -o __ultrwin__.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  -c cl2bp.cc-o cl2bp.o
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  -c cl2bp_lib.cc -o cl2bp_lib.o
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  medfilt1.cc-o medfilt1.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  remez.cc -oremez.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  sosfilt.cc -o sosfilt.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  upfirdn.cc -o upfirdn.oct
make: Leaving directory '/tmp/oct-PGQolD/signal-1.4.0/src'

pkg: error running `make' for the signal package.
error: called from
    configure_make at line 99 column 9
    install at line 184 column 7
    pkg at line 441 column 9

pkg install -forge signal
upfirdn.cc:24:10: fatal error: octave/gripes.h: No such file or directory
 #include <octave/gripes.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:43: upfirdn.oct] Error 1
make: *** Waiting for unfinished jobs....
sosfilt.cc:24:10: fatal error: octave/gripes.h: No such file or directory
 #include <octave/gripes.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:43: sosfilt.oct] Error 1
cl2bp.cc: In function ‘octave_value_list Fcl2bp(const octave_value_list&, int)’:
cl2bp.cc:92:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(0));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:92:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(0));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:97:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(1));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:97:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(1));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:102:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(2));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:102:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(2));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:107:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(3));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:107:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(3));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:112:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(4));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:112:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(4));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
cl2bp.cc:129:5: error: ‘gripe_wrong_type_arg’ was not declared in this scope
     gripe_wrong_type_arg ("cl2bp", args(5));
     ^~~~~~~~~~~~~~~~~~~~
cl2bp.cc:129:5: note: suggested alternative: ‘err_wrong_type_arg’
     gripe_wrong_type_arg ("cl2bp", args(5));
     ^~~~~~~~~~~~~~~~~~~~
     err_wrong_type_arg
medfilt1.cc: In function ‘octave_value_list Fmedfilt1(const octave_value_list&, int)’:
medfilt1.cc:362:22: warning: format ‘%d’ expects argument of type ‘int’,but argument 2 has type ‘octave_idx_type’ {aka ‘long int’} [-Wformat=]
               error ("medfilt1: DIM must be positive, not %d", dim);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
remez.cc: In function ‘octave_value_list Fremez(const octave_value_list&, int)’:
remez.cc:792:17: error: ‘NINT’ was not declared in this scope
   int numtaps = NINT (args(0).double_value()) + 1; // #coeff = filter order+1
                 ^~~~
remez.cc:792:17: note: suggested alternative: ‘NAN’
   int numtaps = NINT (args(0).double_value()) + 1; // #coeff = filter order+1
                 ^~~~
                 NAN
make: *** [Makefile:40: cl2bp.o] Error 1
make: *** [Makefile:43: remez.oct] Error 1
make: Entering directory '/tmp/oct-PGQolD/signal-1.4.0/src'
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  __fwht__.cc-o __fwht__.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  __ultrwin__.cc -o __ultrwin__.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  -c cl2bp.cc-o cl2bp.o
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  -c cl2bp_lib.cc -o cl2bp_lib.o
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  medfilt1.cc-o medfilt1.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  remez.cc -oremez.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  sosfilt.cc -o sosfilt.oct
/app/bin/mkoctfile-5.1.0 -Wall -Wno-deprecated-declarations  upfirdn.cc -o upfirdn.oct
make: Leaving directory '/tmp/oct-PGQolD/signal-1.4.0/src'

pkg: error running `make' for the signal package.
error: called from
    configure_make at line 99 column 9
    install at line 184 column 7
    pkg at line 441 column 9

Using Flatpak ubuntu 18.04 64bit Octave 5.1

**Comment by mtmiller** [comment]
This isn't a Flatpak packaging problem, the signal package 1.4.0 does not install in Octave 5. You'll need to use signal version 1.4.1, which is pending release by the Octave Forge team.
