### ISSUE TITLE
(pulse)Audio is not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by bagustris** [flathub/org.octave.Octave#54]
I just install Octave 5.1 via flatpak. One issue I am facing now is about playing sound with `sound(x, fs)` command. It gives error.

~~~
>> sound(x, fs)
>> ALSA lib ../../../src/pcm/pcm.c:8424:(snd_pcm_recover) underrun occurred
~~~

I use Ubuntu 16.04 and install flatpak from repository.

**Comment by mtmiller** [comment]
This works for me, so doesn't seem to be a problem with the packaging. Can you try another flatpak app to compare and see if sound works for you at all?
