### ISSUE TITLE
issue with oct2py

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#56]
I suffer this issue: https://github.com/blink1073/oct2py/issues/144

In short, I get the following error: error: save: unable to open output file '/tmp/tmp0twzvs0u/reader.mat'

Somehow writer.mat is there, but reader.mat is not. Could it be an issue of the flatpak package somehow? Or perhaps upstream Octave? Or do you think it may be in oct2py itself?

**Comment by mtmiller** [comment]
Oct2Py runs Octave as a child process. How are you using Oct2Py with Flatpak? Is Python running inside the container or outside the container?

If I can guess, you are running Python on your host OS, and Oct2Py is running the org.octave.Octave Flatpak app as a subprocess. If that's right, then yes, the /tmp directory is not shared by design between the host OS and the Flatpak container. See [this message](https://lists.gnu.org/archive/html/help-octave/2019-01/msg00008.html) for a similar problem.

**Comment by kupiqu** [comment]
> Oct2Py runs Octave as a child process. How are you using Oct2Py with Flatpak? Is Python running inside the container or outside the container?
> 
> If I can guess, you are running Python on your host OS, and Oct2Py is running the org.octave.Octave Flatpak app as a subprocess. If that's right, then yes, the /tmp directory is not shared by design between the host OS and the Flatpak container. See [this message](https://lists.gnu.org/archive/html/help-octave/2019-01/msg00008.html) for a similar problem.

Thanks Mike, this is very helpful. I run Octave from a conda environment in my host OS indeed.

I think I will create a fake octave executable with `flatpak run --filesystem=/tmp org.octave.Octave` to be used exclusively by Oct2Py, only. I think it's probably the best available option, or would you suggest another alternative?

In any case, I think we can close this issue.

**Comment by mtmiller** [comment]
Sure, if it works for you. I would probably encourage the Oct2Py developers to try to design a better IPC scheme, using files in /tmp for IPC is hacky at best.

**Comment by kupiqu** [comment]
> fake octave executable with `flatpak run --filesystem=/tmp org.octave.Octave`

Unfortunately Oct2Py doesn't work with such a fake executable. I imagine that the issue is that the process of the fake executable and that of the real octave process obviously do not match, so communication fails. The only solution I see at the moment is to specify the same tmp folder at both ends, but I don't know how to make octave do it only in the context of Oct2Py... :(

> I would probably encourage the Oct2Py developers to try to design a better IPC scheme, using files in /tmp for IPC is hacky at best.

I would agree but I don't know the best way to approach this. Perhaps, if you would agree, I could mention it in Oct2Py's end and refer to you for the case more technical discussion between Oct2Py and Flatpak's Octave is needed.

**Comment by kupiqu** [comment]
"fixed" it with: `flatpak override --filesystem=/tmp org.octave.Octave`

not ideal, but works

**Comment by kupiqu** [comment]
@mtmiller do you know if there is a way to quit Octave when one doesn't have direct access to it. I mean for instance in the context of Oct2Py when Python crashes and Octave remains alive in background. Right now I couldn't find other way than killing its process with kill -9, which is rather drastic (other softer versions of kill not even work, maybe because of flatpak permissions?). Perhaps you know a better way, perhaps even without having to kill the process but just quitting somehow. Thanks in advance

**Comment by mtmiller** [comment]
>  do you know if there is a way to quit Octave when one doesn't have direct access to it

Octave can be controlled with stdin and with signals. If you lost stdin because Python crashed, then all you have left is kill. There is an open bug report that Octave doesn't respond immediately to SIGTERM for example, it takes a SIGTERM followed by a newline on stdin.

**Comment by kupiqu** [comment]
I see, thanks for the info.

> There is an open bug report that Octave doesn't respond immediately to SIGTERM for example, it takes a SIGTERM followed by a newline on stdin.

Do you remember the bug ID? I'd like to take a look.

**Comment by mtmiller** [comment]
[Octave#54444](https://savannah.gnu.org/bugs/?54444)

**Comment by kupiqu** [comment]
Thank you
