### ISSUE TITLE
flatpak compatibility with octave-pythonic

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#57]
I just found out about https://gitlab.com/mtmiller/octave-pythonic
I tried to compile it but configure fails:

```
checking for octave-config filename... specified /var/lib/flatpak/app/org.octave.Octave/current/active/files/bin/octave-config
checking for Octave library path... /app/lib/octave/5.1.0
checking for Octave include path... /app/include/octave-5.1.0/octave
checking whether linking to Octave works... no
configure: WARNING:
========================================================================
Can not link with Octave.

Make sure the Octave development package is installed.
========================================================================

```

**Comment by mtmiller** [comment]
Works for me. You didn't show how you're trying to use it, but

```
checking for octave-config filename... specified /var/lib/flatpak/app/org.octave.Octave/current/active/files/bin/octave-config
```

looks suspicious.

**Comment by kupiqu** [comment]
Fair enough :)

I guess my question is, how do I make octave-pythonic aware of octave and octave-config when they come from a flatpak container?

**Comment by kupiqu** [comment]
If I simply do `.configure` I get this error: `configure: error: unable to find Octave development files`

If I do `./configure --with-octave /var/lib/flatpak/app/org.octave.Octave/current/active/files/bin` I get this error:

```
checking build system type... Invalid configuration `/var/lib/flatpak/app/org.octave.Octave/current/active/files/bin': machine `/var/lib/flatpak/app/org.octave.Octave/current/active/files/bin' not recognized
configure: error: /bin/bash build-aux/config.sub /var/lib/flatpak/app/org.octave.Octave/current/active/files/bin failed
```

At some point I also tried to create soft links to octave and octave-config in a local bin path, and I think it was when I got the error I reported in the first place (sorry, not 100% sure as I tried few alternatives, but no one seemed to work).

**Comment by kupiqu** [comment]
I saw in the git repo that you are actively working to create an octave package for octave-pythonic. I think I'll just wait until it is ready :)
