### ISSUE TITLE
graphicsmagick compilation to use 16 bits

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#58]
According to https://wiki.octave.org/GraphicsMagick graphicsmagick should be compiled to use 16 bits. Debian, Ubuntu and Red Hat do this already, but it seems it's not the case in Octave's flatpak container.

**Comment by mtmiller** [comment]
Good catch, yes definitely.

**Comment by kupiqu** [comment]
Would you please consider releasing a new version of the flatpak package with graphicsmagick compiled to use 16 bits? It would be very appreciated, thanks in advance!

**Comment by kupiqu** [comment]
Great, thanks
