### ISSUE TITLE
gs not installed

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#59]
[ Sorry if this is not the right place to fill this issue, but I'm not sure if this is an issue in flatpak's build or an issue in Octave upstream. Filling the issue here first so I can get your feedback ]

I get the following error even though I use a try-catch instruction:

```
try
  print('-depsc','figname.eps','-tight');
catch
  print('-depsc','figname.eps');
end_try_catch
```

Error:

```
sh: -h: command not found
free(): double free detected in tcache 2
sh line 1:    26 Aborted                 /app/bin/epstool --quiet --copy --bbox /tmp/oct-xrM3rR.eps 'figname.eps'
```

**Comment by kupiqu** [comment]
This is a complete example:

```
> plot(1:10)
> print('-depsc','figname.eps','-tight')
warning: your version of GraphicsMagick limits images to 8 bits per pixel
warning: print.m: Ghostscript binary is not available.  Only eps output is possible
warning: called from
    __print_parse_opts__ at line 487 column 7
    print at line 416 column 8
sh: -h: command not found
free(): double free detected in tcache 2
sh línia 1:    27 Aborted                /app/bin/epstool --quiet --copy --bbox /tmp/oct-6PiVJ2.eps 'figname.eps'
```

it fails with the '`-tight'` option, even in a try-catch instruction as mentioned above

**Comment by kupiqu** [comment]
Not sure if this is part of the issue: `warning: print.m: Ghostscript binary is not available.  Only eps output is possible`

**Comment by mtmiller** [comment]
Yes, it is exactly the issue. I think an appropriate Octave upstream bug would be "print -tight only warns, does not error when ghostscript binary not found".

**Comment by mtmiller** [comment]
And for this package, why isn't `gs` found? We do build ghostscript as part of the app, maybe something's wrong there.

**Comment by kupiqu** [comment]
> And for this package, why isn't `gs` found? We do build ghostscript as part of the app, maybe something's wrong there.

Mmm, so it might be the two, an upstream issue + another one in flatpak wrt gs. Will fill the upstream part...

Thanks!

**Comment by kupiqu** [comment]
upstream issue reported: https://savannah.gnu.org/bugs/index.php?56193

**Comment by mtmiller** [comment]
Should we turn this into "gs not installed" or start a new issue?

**Comment by mtmiller** [comment]
Confirmed in a local build. I think [this section](https://github.com/flathub/org.octave.Octave/blob/a9ff763a0301bd518e5a98d864a7eb05001c0ba2/org.octave.Octave.yaml#L112-L115) is not doing what was intended. It's overwriting ghostscript source with libpng source and only building and installing libpng.

Cc @Alexander-Wilms

**Comment by Erick555** [comment]
While at you may bump gs to 9.27 which fixes some security issues.

**Comment by kupiqu** [comment]
I wonder, has this been released? I'm still suffering this issue

**Comment by mtmiller** [comment]
This has not been published yet, build currently fails due to unrelated #64.

**Comment by kupiqu** [comment]
> This has not been published yet, build currently fails due to unrelated #64.

Ok, I see, thanks for the information
