### ISSUE TITLE
Octave - Cantor communication fails when both are installed via flatpak containers

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#60]
I can make Cantor communicate with Octave (one of its 11 possible backends; https://edu.kde.org/cantor/) with no issue, even when Octave is installed via flatpak.

However, when both of them are installed as flatpak containers things go wrong.

I could workaround the first issue, and make Octave visible to Cantor doing:

sudo flatpak override --filesystem=/var org.kde.cantor

However, executing any Octave instruction in Cantor makes Cantor go crazy, presumably waiting for Octave's response that is never reached, triggering a 100% CPU issue.

I assume I'm missing sth or doing it wrong, so I wonder, is there a way to allow interaction/communication between two flatpak packages?

I know this is a rather abstract/general issue, but I'm out of ideas, and thought that perhaps you have some clue of what could be failing...

[ Upstream flatpak report: https://github.com/flatpak/flatpak/issues/2846 ]

**Comment by mtmiller** [comment]
Seems likely, I don't think Flatpak apps are meant to be nested at all. Typically IPC between/among containerized apps happens over network sockets or D-Bus.

**Comment by kupiqu** [comment]
I see. I think it makes sense. 

It would be nice to have an override or some kind of config option for letting 2+ flatpak packages share the same environment.
