### ISSUE TITLE
[Bug] Octave "failed to load driver" 

### ISSUE THREAD

**Issue by alexpattyn** [flathub/org.octave.Octave#63]
# Issue

When I open octave on a Ubuntu 18.04.2 system with amdgpu-pro installed I get the following errror.

**Octave's Terminal**

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
GNU Octave, version 5.1.0
```

# Reproduce

1. Installed `./amdgpu-pro-install --opencl=pal` from https://www.amd.com/en/support (**I have a radeon VII**)

2. Install flatpaked Octave **and** the version of Octave from Ubuntu's repos (4.2.2).

3. Open flatpaked Octave and see the above error. If you plot anything i.e. `imagesc(my_image)` octave crashes. This issue doesn't appear on the version of Octave that is from Ubuntu's repos (4.2.2).

So perhaps this is an issue with flatpak not working with drivers that are installed from external sources? However, I also have access to a NVIDIA system with proprietary drivers installed and didn't see this issue.

**Comment by alexpattyn** [comment]
Also another possibility is that I did install ROCm and then uninstalled it to get amdgpu-pro working. This may have lead to issues too. So when I get a chance I can try to do a fresh install.

**Comment by mtmiller** [comment]
Does setting `LIBGL_ALWAYS_SOFTWARE=1` in the environment work around the error messages and the crash? For example

    env LIBGL_ALWAYS_SOFTWARE=1 flatpak run org.octave.Octave --gui

If that does work for you, then yes, it seems like it may be an issue with Flatpak and the installed video driver that may not be compatible with the Mesa stack in the Flatpak container.

**Comment by alexpattyn** [comment]
Issuee still occurs with...

```bash
$ env LIBGL_ALWAYS_SOFTWARE=1 flatpak run org.octave.Octave --gui

Gtk-Message: 14:21:00.760: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:21:00.760: Failed to load module "canberra-gtk-module"
octave exited with signal 11
```
When octave launched I typed...

```octave
temp = ones(10,10);
imagesc(temp)
```
Which then crashed octave.

**Comment by mtmiller** [comment]
The best next step would be to roll back the video drivers or try again on a fresh install without any external video drivers added.

**Comment by alexpattyn** [comment]
Haven't had this problem since I opened the issue. Currently I am using the opensource drivers with ROCm 2.7 (opencl only) and everything seems fine.
