### ISSUE TITLE
build fails due to missing content_rating AppStream tag

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#64]
Flatpak build fails to due AppStream validation. A new requirement is that appdata must contain a `content_rating` tag.

```
builddir/files/share/appdata/org.octave.Octave.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
Validation of files failed
```

Example failed build: https://flathub.org/builds/#/builders/32/builds/4411

This needs the appdata file to be patched to include a `content_rating`, or worked around in some other way.

This is also tracked upstream at [Octave#56466](https://savannah.gnu.org/bugs/?56466), but fixing it here doesn't need to wait on upstream.

**Comment by mtmiller** [comment]
Clarification question posed at https://github.com/hughsie/oars/issues/27

**Comment by bksubhuti** [comment]
i made my appstream file with the appstream helper linked from flatpak.  It would be *nice* if this was included in xml making application
