### ISSUE TITLE
Octave-gui crashed and the error: octave exited with signal 6

### ISSUE THREAD

**Issue by XuRongYan** [flathub/org.octave.Octave#65]
My octave version is 5.1.0 and my qt version is 5.12.3, all installed by homebrew.
But it crashed. 
I have tried the method in #17 but the octave5.1.0 only support qt5.12.0 or later
any solution?

**Comment by mtmiller** [comment]
> all installed by homebrew.

If you're using homebrew, I think you've landed on the wrong issue tracker. This repository is for Octave built for Flatpak.

**Comment by phantomromeo** [comment]
> 
> 
> My octave version is 5.1.0 and my qt version is 5.12.3, all installed by homebrew.
> But it crashed.
> I have tried the method in #17 but the octave5.1.0 only support qt5.12.0 or later
> any solution?

I'm having the same issue... 
Octave 6.2, installed with Flatpak. Runned with command line "flatpak run --device=all org.octave.Octave --gui".
My octave script is using "sockets", "control" and "signal" packages.

Anyone has a solution ?

**Comment by mtmiller** [comment]
> I'm having the same issue...

Please file a new issue.
