### ISSUE TITLE
flatpak update: Warning: Can't find app/org.octave.Octave/x86_64/stable metadata for dependencies

### ISSUE THREAD

**Issue by PyDataBlog** [flathub/org.octave.Octave#78]
I have installed Octave via flatpak (Ubuntu 18.04) and lately running `flatpak update`  gives the following error:

`flatpak update: Warning: Can't find app/org.octave.Octave/x86_64/stable metadata for dependencies: Unable to load metadata from remote flathub: summary fetch error: TLS support is not available
`

How can correct this issue?

**Comment by mtmiller** [comment]
You reported this already as #72, and I gave you some feedback on that issue. Please don't continue to report the same issue again and again.

**Comment by PyDataBlog** [comment]
Oh my bad. I actually thought I was reporting it to upstream Flatpak.
