### ISSUE TITLE
installing miscellaneous package fails

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#79]
```
pkg install -forge miscellaneous
```
```
configure: error: The program GNU Units is required to install Octave-Forge miscellaneous package.
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking term.h usability... yes
checking term.h presence... yes
checking for term.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for units... no

pkg: error running the configure script for miscellaneous.
error: called from
    configure_make at line 82 column 9
    install at line 184 column 7
    pkg at line 441 column 9
```

**Comment by kupiqu** [comment]
There are other packages that fail as well. I cannot update the nan package from 3.1.4 to latest, and cannot install communications package either.

Should I open other issues or use this one as a generic issue for installing/updating packages as they appear? 

I will update the title of this issue or open new ones accordingly...

**Comment by mtmiller** [comment]
Let's keep issues small and fixable. This one will be fixed by including `units` in the container.

As for opening other issues, it depends on the error. If a package fails to build because it doesn't work with Octave 5 (like communications), then there's not much we can do about that. If it's because it's missing some program or utility, then maybe we can. If in doubt, do open new issues.

**Comment by kupiqu** [comment]
> Let's keep issues small and fixable. This one will be fixed by including units in the container.

It makes sense.

> If a package fails to build because it doesn't work with Octave 5 (like communications), then there's not much we can do about that.

I know this discussion doesn't belong here, but this is strange from a user point of view. Shouldn't packages need to be compatible with latest stable version?

Not sure what really is the problem with the `nan` package, will check it out and report the error if it still happens in a different issue.

**Comment by kupiqu** [comment]
Thanks!
