### ISSUE TITLE
error: javaMethod: /usr/local/java/libjvm.so: failed to load: /usr/local/java/libjvm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mingwugmail** [flathub/org.octave.Octave#85]
```
$ flatpak run org.octave.Octave
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
GNU Octave, version 5.1.0
Copyright (C) 2019 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> javaclasspath
error: javaMethod: /usr/local/java/libjvm.so: failed to load: /usr/local/java/libjvm.so: cannot open shared object file: No such file or directory
error: called from
    javaclasspath at line 64 column 16

# but on shell
$ ls -l /usr/local/java/libjvm.so
lrwxrwxrwx 1 root root 32 Jan  4 06:29 /usr/local/java/libjvm.so -> ./jre/lib/amd64/server/libjvm.so
```

looks like "/usr/local/java/libjvm.so" is a hard coded path pointing to some relative path inside  in the flatpak system?

**Comment by mtmiller** [comment]
I think you have `JAVA_HOME=/usr/local/java` in your environment. Can you verify and try again with `JAVA_HOME` unset? Works for me.

**Comment by mingwugmail** [comment]
it worked somehow like this:

```
$ export JAVA_HOME=
$ flatpak run org.octave.Octave
...
octave:1> javaclasspath
   STATIC JAVA PATH

      - empty -

   DYNAMIC JAVA PATH

      - empty -

octave:3> pkg load io
octave:4> [a,b,c]=xlsread('abc.xls');
Detected XLS interfaces: None.
warning: xlsopen.m: no '.xls' spreadsheet I/O support with available interfaces.
error: element number 1 undefined in return list
```

I'm wondering how to make `xlsread` function call work?

Thanks.

**Comment by mingwugmail** [comment]
Another try:

```
$ flatpak run org.octave.Octave
...
octave:1> pkg load io
octave:2> chk_spreadsheet_support
ans = 0
octave:3> chk_spreadsheet_support ('', 0, '/usr/lib/libreoffice/program/classes')
ans = 0
octave:4> chk_spreadsheet_support ('/usr/lib/libreoffice/program/classes')
ans = 0
octave:5> quit;

$ ls /usr/lib/libreoffice/program/classes
java_uno.jar  juh.jar  jurt.jar  ridl.jar  unoloader.jar
```

why chk_spreadsheet_support  cannot pickup the java_uno.jar as doc-ed here:

http://wiki.octave.org/IO_package#Java_example

**Comment by mtmiller** [comment]
All Flatpak apps are sandboxed, and do not have access to the host `/usr` filesystem (read more about [sandbox permissions](https://docs.flatpak.org/en/latest/sandbox-permissions.html)).

If you want to load the LibreOffice class files in Flatpak Octave, you could try copying them to your home directory, which _is_ accessible, for example

    mkdir -p ~/libreoffice-classes
    cp -a /usr/lib/libreoffice/program/classes/*.jar ~/libreoffice-classes

**Comment by mingwugmail** [comment]
I tried, but those jars are still not picked up, and I cannot read the .xls file:

```
octave:5> ls ~/octave/jars
java_uno.jar  juh.jar  jurt.jar  ridl.jar  unoloader.jar

octave:7> chk_spreadsheet_support
ans = 0
octave:8> chk_spreadsheet_support('~/octave/jars')
ans = 0
```

Can you show me the instructions on how to load these jars and make xlsread an .xls file work on Linux?

Thanks!

**Comment by mtmiller** [comment]
Sorry, I probably know less about the IO package than you do. The simplest answer I've seen is to download the JXL jar file and add it to the class path

    >> javaaddpath ("~/jars/jxl.jar");
    >> chk_spreadsheet_support
    ans = 8

If you need more help with the IO package, best to send a message to the [help-octave mailing list](https://lists.gnu.org/mailman/listinfo/help-octave).

**Comment by mingwugmail** [comment]
Thank you! It worked.

Maybe add these instructions as an FAQ item or make it work as in the default installation so octave can work out of box? reading spreadsheet is such a common thing to load data.

**Comment by mtmiller** [comment]
The [IO package wiki page](https://wiki.octave.org/IO_package) contains the best information on which third-party programs or Java libs you need for different file formats. It's a wiki, so please help improve the information there if you can.

Bundling any Java libs should probably be part of the IO package itself, if it's done at all, not part of the Octave app. For now, the IO package only documents what the user can download own their own.
