### ISSUE TITLE
cannot install netcdf

### ISSUE THREAD

**Issue by grgdll** [flathub/org.octave.Octave#86]
Hi,
I've just installed octave-5.1.0 on fedora29 (Octave was configured for "x86_64-pc-linux-gnu")
using flatpak (that I discovered today).

I now need to install the netcdf octave-forge package and I have tried, from within octave the following with the following results:

> octave:1> pkg install -forge -verbose netcdf
> mkdir (/tmp/oct-ZQmLv9)
> untar (netcdf-1.0.12.tar.gz, /tmp/oct-ZQmLv9)
> checking for gawk... gawk
> checking whether the C++ compiler works... yes
> checking for C++ compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking for mkoctfile... /app/bin/mkoctfile-5.1.0 --verbose
> checking for octave... /app/bin/octave-5.1.0
> checking for nc-config... no
> configure: error: nc-config not found
> 
> pkg: error running the configure script for netcdf.
> error: called from
>     configure_make at line 82 column 9
>     install at line 184 column 7
>     pkg at line 441 column 9
> octave:1>

 

However, if, after quitting octave I try this `which nc-config`, I get this `~/miniconda3/bin/nc-config`.

my PATH contains ~/miniconda3/bin

Can anybody help please?

Many thanks in advance,
grg

**Comment by mtmiller** [comment]
Your user PATH is not preserved when running a Flatpak app. Can you try adding ~/miniconda3/bin back into your PATH in Octave and try installing the package again? For example

    setenv ("PATH", [tilde_expand("~/miniconda3/bin"), pathsep, getenv("PATH")])
    pkg install -forge -verbose netcdf

**Comment by grgdll** [comment]
thanks for the fast reply: after following your suggestion, things moved further, but there still is an error I am not sure how to deal with:
```
octave:1> setenv ("PATH", [tilde_expand("~/miniconda3/bin"), pathsep, getenv("PATH")])
octave:2> pkg install -forge -verbose netcdf
mkdir (/tmp/oct-Fep0S4)
untar (/home/netcdf-1.0.12.tar.gz, /tmp/oct-Fep0S4)
checking for gawk... gawk
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for mkoctfile... /app/bin/mkoctfile-5.1.0 --verbose
checking for octave... /app/bin/octave-5.1.0
checking for nc-config... nc-config
checking for netcdf4 support... yes
checking   is_empty or isempty... isempty
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h

octave-forge is configured with
   octave:        /app/bin/octave-5.1.0
   mkoctfile:	  /app/bin/mkoctfile-5.1.0 --verbose
   nc-config:     nc-config
   netCDF compiler flags: -I/home/miniconda3/include
   netCDF libraries: -L/home/miniconda3/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl

make: Entering directory '/tmp/oct-Fep0S4/netcdf-1.0.12/src'
gawk -f netcdf_constants.awk /home/miniconda3/include/netcdf.h  > netcdf_constants.h
gawk: netcdf_constants.awk:21: warning: regexp escape sequence `\#' is not a known regexp operator
/app/bin/mkoctfile-5.1.0 --verbose -v -I/home/miniconda3/include __netcdf__.cc -L/home/miniconda3/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl
g++ -c -I/app/include -fPIC -I/app/include/octave-5.1.0/octave/.. -I/app/include/octave-5.1.0/octave -I/app/include  -pthread -fopenmp -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -grecord-gcc-switches   -I/home/miniconda3/include  __netcdf__.cc -o /tmp/oct-5sj41E.o
g++ -I/app/include/octave-5.1.0/octave/.. -I/app/include/octave-5.1.0/octave -I/app/include  -pthread -fopenmp -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -grecord-gcc-switches -shared -Wl,-Bsymbolic -L/app/lib  -o __netcdf__.oct  /tmp/oct-5sj41E.o   -L/home/miniconda3/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl  -L/app/lib  -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed
make: Leaving directory '/tmp/oct-Fep0S4/netcdf-1.0.12/src'
copyfile /tmp/oct-Fep0S4/netcdf-1.0.12/src/__netcdf__.oct /tmp/oct-Fep0S4/netcdf-1.0.12/inst/x86_64-pc-linux-gnu-api-v53
/home/octave/netcdf-1.0.12/x86_64-pc-linux-gnu-api-v53/__netcdf__.oct: failed to load: libnetcdf.so.13: cannot open shared object file: No such file or directory
error: called from
    doc_cache_create>create_cache at line 109 column 20
    gen_doc_cache_in_dir>@<anonymous> at line 143 column 16
    doc_cache_create>gen_doc_cache_in_dir at line 144 column 9
    doc_cache_create at line 55 column 12
    install>generate_lookfor_cache at line 794 column 5
    install at line 223 column 7
    pkg at line 441 column 9
```

It looks like it cannot find `libnetcdf.so.13`, but I am not sure how to check where this file or if I have it.

Any help will be greatly appreciated.
Cheers!
grg

**Comment by grgdll** [comment]
OK, I've checked and `libnetcdf.so.13` is in `home/miniconda3/lib`.

It still does not work even if I add this to the Octave path with 
`setenv ("PATH", [tilde_expand("~/miniconda3/lib"), pathsep, tilde_expand("~/miniconda3/bin"), pathsep, getenv("PATH")])`

I'm lost, please help!
grg

**Comment by mtmiller** [comment]
You probably want to also set LD_LIBRARY_PATH to include ~/miniconda3/lib. This isn't Anaconda specific, would be needed for any program linking to a library in a non-standard directory. You'll need this set in your environment any time you use the netcdf package, not just when installing.

If you think that's inconvenient, you might ask the netcdf package maintainer to consider building with the `-rpath` option to bake the library directory in at install time.

**Comment by grgdll** [comment]
I added LD_LIBRARY_PATH to include ~/miniconda3/lib and now I cannot start Octave anymore...
```
grgdll:~$ export LD_LIBRARY_PATH=/home/miniconda3/lib/
grgdll:~$ echo $LD_LIBRARY_PATH
/home/miniconda3/lib/
grgdll:~$ flatpak run  org.octave.Octave --no-gui
flatpak: /home/miniconda3/lib/libuuid.so.1: no version information available (required by /lib64/libappstream-glib.so.8)
flatpak: /home/miniconda3/lib/libuuid.so.1: no version information available (required by /lib64/libblkid.so.1)
flatpak: symbol lookup error: /lib64/librpmio.so.8: undefined symbol: EVP_md2, version OPENSSL_1_1_0
```

**Comment by mtmiller** [comment]
Try setting LD_LIBRARY_PATH in Octave rather than the calling shell

    setenv ("LD_LIBRARY_PATH", tilde_expand("~/miniconda3/lib"))

**Comment by grgdll** [comment]
it does not seem to have changed much 

```
octave:1> setenv ("PATH", [tilde_expand("~/miniconda3/bin"), pathsep, getenv("PATH")])
octave:2> setenv ("LD_LIBRARY_PATH", tilde_expand("~/miniconda3/lib"))
octave:3> pkg install -forge -verbose netcdf
mkdir (/tmp/oct-bwbYVE)
untar (/home/netcdf-1.0.12.tar.gz, /tmp/oct-bwbYVE)
checking for gawk... gawk
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for mkoctfile... /app/bin/mkoctfile-5.1.0 --verbose
checking for octave... /app/bin/octave-5.1.0
checking for nc-config... nc-config
checking for netcdf4 support... yes
checking   is_empty or isempty... isempty
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h

octave-forge is configured with
   octave:        /app/bin/octave-5.1.0
   mkoctfile:	  /app/bin/mkoctfile-5.1.0 --verbose
   nc-config:     nc-config
   netCDF compiler flags: -I/home/miniconda3/include
   netCDF libraries: -L/home/miniconda3/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl

make: Entering directory '/tmp/oct-bwbYVE/netcdf-1.0.12/src'
gawk -f netcdf_constants.awk /home/miniconda3/include/netcdf.h  > netcdf_constants.h
gawk: netcdf_constants.awk:21: warning: regexp escape sequence `\#' is not a known regexp operator
/app/bin/mkoctfile-5.1.0 --verbose -v -I/home/miniconda3/include __netcdf__.cc -L/home/miniconda3/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl
g++ -c -I/app/include -fPIC -I/app/include/octave-5.1.0/octave/.. -I/app/include/octave-5.1.0/octave -I/app/include  -pthread -fopenmp -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -grecord-gcc-switches   -I/home/miniconda3/include  __netcdf__.cc -o /tmp/oct-6uI8FC.o
g++ -I/app/include/octave-5.1.0/octave/.. -I/app/include/octave-5.1.0/octave -I/app/include  -pthread -fopenmp -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong -grecord-gcc-switches -shared -Wl,-Bsymbolic -L/app/lib  -o __netcdf__.oct  /tmp/oct-6uI8FC.o   -L/home/miniconda3/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lrt -lpthread -lz -ldl -lm -lcurl  -L/app/lib  -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed
make: Leaving directory '/tmp/oct-bwbYVE/netcdf-1.0.12/src'
copyfile /tmp/oct-bwbYVE/netcdf-1.0.12/src/__netcdf__.oct /tmp/oct-bwbYVE/netcdf-1.0.12/inst/x86_64-pc-linux-gnu-api-v53
/home/octave/netcdf-1.0.12/x86_64-pc-linux-gnu-api-v53/__netcdf__.oct: failed to load: libnetcdf.so.13: cannot open shared object file: No such file or directory
error: called from
    doc_cache_create>create_cache at line 109 column 20
    gen_doc_cache_in_dir>@<anonymous> at line 143 column 16
    doc_cache_create>gen_doc_cache_in_dir at line 144 column 9
    doc_cache_create at line 55 column 12
    install>generate_lookfor_cache at line 794 column 5
    install at line 223 column 7
    pkg at line 441 column 9
```

**Comment by mtmiller** [comment]
Ok, that confirms LD_LIBRARY_PATH is only read once when Octave starts.

Try this instead

    flatpak run --env=LD_LIBRARY_PATH=$HOME/miniconda3/lib org.octave.Octave

**Comment by grgdll** [comment]
It worked!!!
I have now successfully installed netcdf (and changed my octave alias to include the suggested --env specification).
Many many thanks for your precious help.

**Comment by mtmiller** [comment]
Ok, closing as resolved. If I were the netcdf package maintainer, I would want to make this easier, so I would investigate adding the `-rpath` option to the build rules so the user doesn't have to set LD_LIBRARY_PATH. You might want to suggest that change in a new bug report [here](https://savannah.gnu.org/bugs/?func=additem&group=octave).

**Comment by grgdll** [comment]
Hello again,
I think I have spoken too soon.
Last night I was connecting from home using ssh (without the -X option) to my computer at work. Thus, the "graphical interface" was not working.
This morning I tried to run octave again from my work desktop and I got this error:
```
grgdll:~$ flatpak run -v --env=LD_LIBRARY_PATH=$HOME/miniconda3/lib  org.octave.Octave
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/.local/share/flatpak
F: Opening user flatpak installation at path /home/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2475397679
F: Allocated instance id 3640620710
F: Add defaults in dir /org/octave/Octave/
F: Add locks in dir /org/octave/Octave/
F: Allowing dri access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Running 'bwrap --args 34 xdg-dbus-proxy --args=36'
F: Running 'bwrap --args 34 octave'
/app/libexec/octave/5.1.0/exec/x86_64-pc-linux-gnu/octave-gui: /home/miniconda3/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /app/lib/octave/5.1.0/liboctgui.so.5)
/app/libexec/octave/5.1.0/exec/x86_64-pc-linux-gnu/octave-gui: /home/miniconda3/lib/libQt5Core.so.5: version `Qt_5.13' not found (required by /app/lib/libqscintilla2_qt5.so.13)
```
I think that now that the "graphical interface" is activated, flatpak or octave are looking for and cannot find the Qt libraries.

How do I let them know where these libraries are?
Many thanks

**Comment by grgdll** [comment]
Note also the following: 
```
grgdll:~$ ls -l miniconda3/lib/libQt5Core*
-rw-rw-r--+ 1 grgdll xxx    1094 Jan 14 10:49 miniconda3/lib/libQt5Core.prl
lrwxrwxrwx. 1 grgdll xxx      19 Jan 14 10:53 miniconda3/lib/libQt5Core.so -> libQt5Core.so.5.9.7
lrwxrwxrwx. 1 grgdll xxx      19 Jan 14 10:53 miniconda3/lib/libQt5Core.so.5 -> libQt5Core.so.5.9.7
lrwxrwxrwx. 1 grgdll xxx      19 Jan 14 10:53 miniconda3/lib/libQt5Core.so.5.9 -> libQt5Core.so.5.9.7
-rwxrwxr-x. 1 grgdll xxx 4270856 Jan 14 10:49 miniconda3/lib/libQt5Core.so.5.9.7
```
So miniconda/lib contains libQt5Core.so.5, but it is an older version than the one required.

How do I tell flapak to look in the correct directory?
And how can I found out where this directory is?

**Comment by grgdll** [comment]
I've solved this last problem by moving the netcdf libraries to a separate dir than miniconda3/lib and by creating links in this new dir to the other libraries that were needed.
However this is not very clean, so it would be great if anybody could suggest a better way of doing it.
thanks in advance

**Comment by mtmiller** [comment]
Sure, if you have a full Anaconda installation including Qt libraries, and you try to run Octave with LD_LIBRARY_PATH pointing there, that will cause problems. I can confirm that Octave's GUI runs with a stock Miniconda install, and fails after `conda install qt`.

It seems like you have a good grasp of the problem and the tradeoffs. You need to point the dynamic linker at the location of libnetcdf.so.13 without conflicting with any of the other system and framework libraries that Octave uses.
