### ISSUE TITLE
very slow start

### ISSUE THREAD

**Issue by grgdll** [flathub/org.octave.Octave#87]
Hi again,
I have recently installed octave (see below my specs) using flatpak.

My issue is that when I start octave 
`flatpak run -v --env=LD_LIBRARY_PATH=$HOME/miniconda3/lib/netcdf  org.octave.Octave`
it takes about 30 seconds until I can actually starting typing in the octave environment.

Specifically the verbose output stops for several seconds after `
F: Add locks in dir /org/octave/Octave/` 
See below the whole verbose output of flatpak.

This is a big nuisance because I'd like to run octave in batch mode...
Has anybody experienced this?
How to solve it?

Many thanks in advance for your help.
grg

```
grgdll:~$ flatpak run -v --env=LD_LIBRARY_PATH=$HOME/miniconda3/lib/netcdf  org.octave.Octave
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/.local/share/flatpak
F: Opening user flatpak installation at path /home/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2244744046
F: Allocated instance id 3206973781
F: Add defaults in dir /org/octave/Octave/
F: Add locks in dir /org/octave/Octave/
F: Allowing dri access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Running 'bwrap --args 34 xdg-dbus-proxy --args=36'
F: Running 'bwrap --args 34 octave'
GNU Octave, version 5.1.0
Copyright (C) 2019 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> ver
----------------------------------------------------------------------
GNU Octave Version: 5.1.0 (hg id: d05d6eebde10)
GNU Octave License: GNU General Public License
Operating System: Linux 5.3.11-100.fc29.x86_64 #1 SMP Tue Nov 12 20:41:25 UTC 2019 x86_64
----------------------------------------------------------------------
Package Name   | Version | Installation directory
---------------+---------+-----------------------
      control  |   3.2.0 | /home/octave/control-3.2.0
    financial  |   0.5.3 | /home/octave/financial-0.5.3
      general  |   2.1.0 | /home/octave/general-2.1.0
           io  |  2.4.13 | /home/octave/io-2.4.13
miscellaneous  |   1.3.0 | /home/octave/miscellaneous-1.3.0
          nan  |   3.4.5 | /home/octave/nan-3.4.5
       netcdf  |  1.0.12 | /home/octave/netcdf-1.0.12
       signal  |   1.4.1 | /home/octave/signal-1.4.1
   statistics  |   1.4.1 | /home/octave/statistics-1.4.1
       struct  |  1.0.16 | /home/octave/struct-1.0.16
```

**Comment by mtmiller** [comment]
Does the delay happen on the first run or every time? This looks like https://github.com/flatpak/flatpak/issues/1768.

Octave starts instantly for me, unreproducible here.

**Comment by grgdll** [comment]
It happens all the times
________________________________________

**Comment by mtmiller** [comment]
Ok, then it looks like some kind of timeout interaction between Flatpak and some system service. Does it affect any Flatpak app or only Octave?

**Comment by grgdll** [comment]
I've only used flatpak for octave.  So I don't know. Sorry
________________________________________

**Comment by grgdll** [comment]
OK, I've now tried with FileZilla and Flatpak and the result is the same:
a long time is spent between here
`F: Add locks in dir /org/filezillaproject/Filezilla/`
and here
`F: Allowing dri access`
any clue?
any other test I could run?
Please let me know.
thanks
grg

**Comment by grgdll** [comment]
OK, thanks for the suggestion to look at other apps.
I found this thread:
https://github.com/flatpak/xdg-desktop-portal/issues/369
Following those suggestions I deleted `~/.local/share/flatpak/db` and now octave starts quickly.
thanks again
grg
