### ISSUE TITLE
update to Octave 5.2.0

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#89]
Will be released later this week. A beta release 5.1.90 is available now for testing.

**Comment by siko1056** [comment]
Now I came a little late for testing.  How can I download / test your beta versions in the future?  Is there a way to list the available branches for org.octave.Octave?

**Comment by mtmiller** [comment]
@siko1056 Test versions are created by the buildbot and referenced in PR comments, as with your PR #90 before being merged.

If I had wanted to make a 5.1.90 test build, I would have just created a PR and left it unmerged.

There is an optional Flathub beta repo, but we haven't published any Octave versions there yet.

**Comment by siko1056** [comment]
@mtmiller Thanks for the explanation.  My idea of your first message was, that you created that flatpak beta, and I am just unable to find the "obvious" link to it :wink:

**Comment by mtmiller** [comment]
Ah, nope, sorry, it was just a reminder to myself / others that the 5.1.90 version is out there to try before you had 5.2.0 tagged.
