### ISSUE TITLE
Recipe for target 'doc/interpreter/octave_interpreter.qch' failed

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.octave.Octave#9]
This error occurs when building the Octave tarball from source.

Cf. https://savannah.gnu.org/bugs/?53371 and https://savannah.gnu.org/bugs/?53368

**Comment by mtmiller** [comment]
As far as I have seen, the word is that the build dependency on Python lxml will be dropped before 4.4.

**Comment by Alexander-Wilms** [comment]
I'm just running the commands in the README.md, so it's the current tip of the default branch.

**Comment by mtmiller** [comment]
I just updated README.md, 4.3.0+ is now the stable branch.

I can't reproduce this. Is the error when you are building the tar with `make dist` or is the error in the flatpak-build?

If it's in the `make dist` then this isn't really an issue here, right? There have been some fixes on stable in the last couple days that might help, but still work to be done on the Qt help generation steps.

**Comment by mtmiller** [comment]
I have a successful build from stable branch to tarball to flatpak, and the Python lxml dependency is dropped now in Octave.

**Comment by Alexander-Wilms** [comment]
```
make dist
make  dist-lzip dist-xz dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory „/home/awilms/Development/org.octave.Octave/octave“
  MAKEINFO AUTHORS
  GEN      ChangeLog
  MAKEINFO BUGS
  MAKEINFO INSTALL.OCTAVE
  GEN      oct-conf-post.h
config.status: creating oct-conf-post.h-tmp
config.status: executing oct-conf-post.h commands
  GEN      octave-config.h
  GEN      libinterp/corefcn/mk-mxarray-h.sh
config.status: creating libinterp/corefcn/mk-mxarray-h.sh-tmp
config.status: executing libinterp/corefcn/mk-mxarray-h.sh commands
  GEN      libinterp/builtin-defun-decls.h
  GEN      liboctave/external/mk-f77-def.sh
config.status: creating liboctave/external/mk-f77-def.sh-tmp
config.status: executing liboctave/external/mk-f77-def.sh commands
  MAKEINFO doc/liboctave/liboctave.info
make[1]: *** No rule exists, to build the target „test/local-functions/subfunctions.tst“, 
 required by „distdir“. Exiting.
make[1]: Verzeichnis „/home/awilms/Development/org.octave.Octave/octave“ wird verlassen
make: *** [Makefile:26631: dist] Error 2
```

**Comment by mtmiller** [comment]
Bad luck, that was an extremely temporary error, broken and fixed a couple hours ago. The current stable rev is 1fa6125c6d08, works for me.
