### ISSUE TITLE
Possibility to create a "64-64" build.

### ISSUE THREAD

**Issue by siko1056** [flathub/org.octave.Octave#91]
Dear Mike,

While another project of mine takes some time for shaping, it would be nice, if there was the possibility to create something like a flatpak "64-64" build, that could be installed by

```
flatpak install flathub org.octave.Octave/x86_64/64-64
```

Is this possible?

**Comment by mtmiller** [comment]
It's technologically possible with Flatpak to create as many branches as you want.

But the policy of Flathub is that there is only one branch per app, called "stable", and it should represent the standard version and build of the application that users would want to install. So no, not in this official repository.

I think what you want to achieve could be done by forking this repo and publishing your own build to your own self-hosted Flatpak repo. And the install command could look something like

    flatpak install https://yourdomain/.../org.octave.Octave.flatpakref

**Comment by siko1056** [comment]
@mtmiller Thanks for the explanation.  In synchronization with the MS Windows builds I'll go with a "new" app "GNU Octave  (64-bit linear algebra for large data)" then.

https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

Flavors of a software really seem unsupported:

https://github.com/flathub/flathub/issues/1138
