### ISSUE TITLE
test failures dealing with complex inf values

### ISSUE THREAD

**Issue by mtmiller** [flathub/org.octave.Octave#93]
Some Octave self-tests dealing with complex inf values fail in the Flatpak build, but pass on the same machine in a native build.

8 test failures in libinterp/corefcn/data.cc, 1 test failure in tests/bug-46330.tst.

For example, sorting this array returns

```
>> sort ([NaN, 1i, -1, Inf, 1, 1i])
ans =

     0 +   1i    -1 +   0i   Inf +   0i     1 +   0i     0 +   1i   NaN +   0i

```

but _should_ return this

```
>> sort ([NaN, 1i, -1, Inf, 1, 1i])
ans =

     1 +   0i     0 +   1i     0 +   1i    -1 +   0i   Inf +   0i   NaN +   0i

```

**Comment by Alexander-Wilms** [comment]
Seems to be fixed in 6.3.0
