### ISSUE TITLE
KDE native file dialog hangs up on Editor menu item "Save File and Run"

### ISSUE THREAD

**Issue by sibskull** [flathub/org.octave.Octave#96]
KDE5, Octave 5.1.0
I type expression in empty Editor tab and choose "Save File and Run" from menu.
There is KDE5 file dialog is appeared. But after several seconds applications hangs up.
If I save code in file (KDE5 file dialog works correct) and after it choose "Save File and Run", it works without problem.
It cannot be reproduced in another DE like Mate and XFCE, only in KDE5.

**Comment by mtmiller** [comment]
The Qt plugin to create native file dialogs for KDE has known problems with Octave. I think this may be another instance of those problems. Can you try again with the "Use native file dialogs" setting disabled?

See https://savannah.gnu.org/bugs/?56116

For curiosity's sake, is your KDE Plasma 5 desktop running on openSUSE?

**Comment by siko1056** [comment]
@mtmiller To make the confusion perfect: This Octave flatpak 5.2.0 build does **not** hang with native file dialogs on openSUSE 15.1 :confused:

**Comment by sibskull** [comment]
No, I use ALT distibution.

**Comment by sibskull** [comment]
I package octave for many DE. And turn off native file dialogs for KDE5 will affect GTK-based users.

**Comment by mtmiller** [comment]
@sibskull Can you confirm that the native file dialog setting fixes this on your KDE Plasma 5 desktop environment?

**Comment by sibskull** [comment]
Yes, uncheck "Use native file dialogs" checkbox fixes this problem.

**Comment by mtmiller** [comment]
Upstream bug report is [Octave #54607](https://savannah.gnu.org/bugs/?54607).

**Comment by kupiqu** [comment]
I cannot reproduce, everything is working fine in KDE neon with Octave 5.2

**Comment by mtmiller** [comment]
It's been suggested upstream that the cause is KIO Samba support, which causes a QProcess to be started when a KDE native file dialog is opened. The QProcess hangs and times out.

If you can't reproduce this with a KDE desktop environment, it may be because you don't have any Samba support installed on your system, or it may be that certain Qt versions aren't affected by this.

**Comment by kupiqu** [comment]
> It's been suggested upstream that the cause is KIO Samba support, which causes a QProcess to be started when a KDE native file dialog is opened. The QProcess hangs and times out.
> 
> If you can't reproduce this with a KDE desktop environment, it may be because you don't have any Samba support installed on your system, or it may be that certain Qt versions aren't affected by this.

Mmm, I see. For the case it is useful, I have Samba installed and works fine. I use Qt libs 5.13.2 withouth issue in my system.

**Comment by mtmiller** [comment]
Wait, @sibskull you said earlier that you are packaging Octave

> I package octave for many DE.

Are you running Octave with flatpak at all when you are affected by this bug? I assumed yes, but I read over this thread and you didn't actually mention flatpak anywhere.

**Comment by sibskull** [comment]
Sorry for delay. I test this issue on Octave 5.2.0 and it is not reproduced. Thanks.

**Comment by ipcoder** [comment]
Reproduced on ubuntu 20.04 KDE.
Hangs in Save File Dialog
Resolved by unchecking "Use native file dialogs"


Octave version 5.2.0

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-48-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8700K CPU @ 3.70GHz
Memory: 31.3 GiB of RAM
